// Public prototype uses only synthetic data. No Firebase, phone list, tokens or real student records.
const content=document.querySelector('#content'),dialog=document.querySelector('#dialog');
const lessons=[['9/14 월','제조 데이터 이해','1일차'],['9/15 화','제조 데이터 이해','2일차'],['9/16 수','공정 데이터 분석','1일차'],['9/17 목','공정 데이터 분석','2일차'],['9/18 금','공정 데이터 분석','3일차']];
const attendance=[['9/14','출석','08:55 → 17:58'],['9/11','인정출석','08:51 → 15:00'],['9/10','출석','08:59 → 17:53'],['9/09','지각','09:35 → 17:55'],['9/08','결석','—'],['9/07','조퇴','08:55 → 15:00'],['9/04','외출','08:52 → 17:58 · 외출 13:00–14:00']];
function show(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
 const stats='<div class="stats">'+['출석','인정출석','결석','지각','조퇴','외출'].map(status=>`<div><strong>${attendance.filter(r=>r[1]===status).length}</strong>${status}</div>`).join('')+'</div>';
 const survey='<div class="alert"><span class="pill">참여 필요</span><h3>제조 데이터 이해 · 만족도조사</h3><p>오늘은 이 강의의 마지막 날이에요. 수업 후 설문에 참여해 주세요.</p><button class="primary" data-demo="survey">설문 참여하기 →</button></div>';
 if(tab==='home')content.innerHTML=`<div class="grid"><div><section class="card"><h2>오늘의 수업</h2><article class="lesson"><small>직무특화</small><h3>제조 데이터 이해 · 2일차</h3><p>09:00–18:00 · 예시 강사 · 우리 반 교육장</p></article><button data-demo="material">강의자료 보기 ↗</button></section><section class="card"><h2>오늘 해야 할 일</h2>${survey}</section></div><div><section class="card"><h2>내 출결 한눈에</h2>${stats}<p class="muted">내 출결만 표시됩니다. 정정이 필요하면 담임에게 문의하세요.</p><button data-go="attendance">내 출결 자세히</button></section><section class="card"><h2>나의 설문 현황</h2><p>참여 완료 <b>5개</b> · 미참여 <b>1개</b></p><button data-go="surveys">설문 전체 보기 →</button></section></div></div>`;
 if(tab==='attendance')content.innerHTML=`<section class="card"><h2>내 출결</h2>${stats}<p class="muted">인정되는 출결은 모두 인정출석으로 표시합니다. 출석·결석·지각·조퇴·외출과 입퇴실 기록을 확인합니다. 아래는 화면 검토용 예시입니다.</p><div class="tablewrap"><table><thead><tr><th>교육일</th><th>출결</th><th>입실 → 퇴실</th></tr></thead><tbody>${attendance.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;
 if(tab==='timetable')content.innerHTML=`<section class="card"><h2>시간표 · 강의자료</h2><p class="muted">9월 14일–18일 · 예시 주간 일정</p><div class="week">${lessons.map((r,i)=>`<article class="day ${i===1?'today':''}"><small>${r[0]} ${i===1?'· 오늘':''}</small><h3>${r[1]}</h3><p>${r[2]} · 09:00–18:00</p><button data-demo="material">강의자료</button>${[1,4].includes(i)?'<p class="pill">모듈 종료일 · 설문 필요</p>':''}</article>`).join('')}</div></section>`;
 if(tab==='surveys')content.innerHTML=`<section class="card"><h2>나의 만족도조사</h2>${survey}<h3>참여 완료</h3><p>공정 기본 이해 · 참여 완료</p><p>디지털스킬 · 참여 완료</p><p class="muted">실제 서비스에서는 내 참여 여부만 보이며, 다른 학생의 응답이나 점수는 표시하지 않습니다.</p></section>`;
 content.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));content.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>{dialog.innerHTML=`<h2>${b.dataset.demo==='material'?'강의자료 연결 예시':'설문 참여 예시'}</h2><p>${b.dataset.demo==='material'?'관리자·담임이 Drive에 올린 자료를 이 강의에 연결하면 여기서 열게 됩니다.':'실제 서비스에서는 해당 강의의 설문 링크로 이동합니다.'}</p><p class="muted">현재는 초안이므로 실제 자료와 설문은 연결하지 않았습니다.</p><button id="close">확인</button>`;dialog.querySelector('#close').onclick=()=>dialog.close();dialog.showModal();});
}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab));
document.querySelector('#signup').onclick=()=>{dialog.innerHTML='<h2>학생 가입 흐름 · 검토용</h2><ol><li>등록된 휴대전화 확인</li><li>문자 인증코드 확인</li><li>아이디·비밀번호 설정</li><li>내 반·내 학생 기록에 연결</li></ol><label>휴대전화<input disabled value="010-••••-0000"></label><label>인증코드<input disabled placeholder="실제 문자는 발송하지 않습니다."></label><p class="muted">개인정보 처리 목적·고지와 인증 제공자 검토 후 실제 가입을 연결할 예정입니다. 이 화면에는 번호나 비밀번호를 입력할 수 없습니다.</p><button id="close">초안으로 돌아가기</button>';dialog.querySelector('#close').onclick=()=>dialog.close();dialog.showModal();};show('home');
