import {summarizeScores} from './survey-scores.mjs';
import {syncAttendanceSummary} from './attendance-derived-store.mjs';
import {targetsFromDerived} from './attendance-derived-core.mjs';
import {cards,pct,scoreChart} from './metrics-ui.mjs';
import {SURVEY_OWNER,eventsForClass,sourceCandidates,summarizeResponses} from './survey-core.mjs';
import {createSurveyStore} from './survey-store.mjs';
import {createSurveyReader} from './survey-google.mjs';
import {createTimetableStore} from './timetable-store.mjs';
import {todayKST} from './timetable-core.mjs';
import {within,readJson} from './attendance-io.mjs';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const validLink=url=>{try{const u=new URL(url);return u.protocol==='https:'&&['docs.google.com','forms.gle'].includes(u.hostname)?u.href:'';}catch{return '';}};
export async function mountSurveys(host,{db,user,classes,teacherClass=null,compact=false,onMore=null}){
 const root=host.shadowRoot||host.attachShadow({mode:'open'}),store=createSurveyStore(db,user),timetables=createTimetableStore(db,user),owner=!teacherClass&&String(user.email||'').toLowerCase()===SURVEY_OWNER;
 root.innerHTML='<link rel="stylesheet" href="/survey.css"><link rel="stylesheet" href="/metrics.css"><div id="surveyContent">만족도조사 일정을 불러오는 중…</div><dialog id="surveyDialog"></dialog>';
 const $=s=>root.querySelector(s),content=$('#surveyContent');let catalog,config={},selected=String(teacherClass?.id||classes[0]?.id||'1'),entries=[],results={},busy=false,classLoading=false,disposed=false,notice='',error='',filter='due',epoch=0,chartWork=null;
 const reader=createSurveyReader(async()=>{const {GoogleAuthProvider,reauthenticateWithPopup}=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js');const p=new GoogleAuthProvider();p.addScope('https://www.googleapis.com/auth/spreadsheets.readonly');p.setCustomParameters({login_hint:SURVEY_OWNER,prompt:'consent'});const r=await reauthenticateWithPopup(user,p),c=GoogleAuthProvider.credentialFromResult(r);if(!c?.accessToken)throw Error('응답 시트 연결을 완료하지 못했습니다.');return c.accessToken;});
 const meta=()=>teacherClass||classes.find(c=>String(c.id)===selected)||{};
 const events=()=>eventsForClass(catalog,selected,entries);
 function resolved(e){const c=config.events?.[e.id]||{},candidates=sourceCandidates(e,catalog.responseSources,meta().course);return {source:catalog.responseSources.find(s=>s.id===c.sourceId)||(candidates.length===1?candidates[0]:null),url:validLink(c.url||e.url),date:c.date||e.date};}
 function list(s,field,label){const a=s?.[field]||[];return `<details ${field==='missing'?'open':''}><summary>${label} ${a.length}명</summary><p>${a.map(x=>esc(x.name)+(x.reason?' <small>('+esc(x.reason)+')</small>':'')).join(' · ')||'없음'}</p></details>`;}
 function render(){if(disposed||!host.isConnected||!catalog)return;let shown=classLoading?[]:events();if(filter==='due')shown=shown.filter(e=>resolved(e).date<=todayKST());
  content.innerHTML=`<div class="top"><div><small>HINT / SURVEY BETA</small><h2>${teacherClass?'우리 반 만족도조사':'만족도조사 · 응답 확인'}</h2><p>해당 수업 마지막 교육일의 출석 기준으로 참여 대상을 대조합니다. 점수는 학생별로 공개하지 않고 문항별 통계로 표시합니다.</p></div></div><div class="toolbar">${teacherClass?'':`<label>반<select id="surveyClass">${classes.map(c=>`<option value="${c.id}" ${String(c.id)===selected?'selected':''}>${c.id}반 · ${esc(c.course)}</option>`).join('')}</select></label>`}<label>표시<select id="surveyFilter"><option value="due" ${filter==='due'?'selected':''}>오늘까지 설문</option><option value="all" ${filter==='all'?'selected':''}>전체 일정</option></select></label><button id="surveyRefresh">새로 읽기</button><button id="surveyCharts">응답률 · 만족도 통계</button>${owner?`<button id="surveyConnect">${reader.connected()?'응답 시트 연결됨':'담당 계정 응답 시트 연결'}</button><button id="surveySync" ${reader.connected()?'':'disabled'}>선택 반 응답 동기화</button><button id="surveyAll" ${reader.connected()?'':'disabled'}>17개 반 순차 동기화</button>`:''}</div><p class="notice" role="status">${esc(error||notice|| (owner?'응답 연결 후 현재 화면에서 10분마다 자동 갱신합니다.':'지정 관리자가 동기화한 마지막 결과를 표시합니다.'))}</p><div class="survey-grid">${shown.map(e=>{const r=resolved(e),s=results[e.id],stale=s&&(s.date!==r.date||s.sourceId!==r.source?.id||s.scheduleFingerprint!==JSON.stringify(entries.filter(x=>e.lessonIds.includes(x.id)).map(x=>[x.id,x.date,x.title,x.day])));return `<section class="survey-card"><header><small>${r.date} · ${selected}반</small><h3>${esc(e.title)}</h3>${r.url?`<a class="button" target="_blank" rel="noopener" href="${esc(r.url)}">설문 참여하기 ↗</a>`:'<span class="warning">참여 링크 미등록</span>'}</header>${!e.scheduleMatched?'<p class="warning">시간표 강의 연결 확인 필요 · 관리 시트 날짜 표시</p>':''}${s?`<p class="muted">마지막 동기화 ${esc(new Date(s.syncedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))}</p>${stale?'<p class="warning">시간표·연결이 바뀌었습니다. 다시 동기화해 주세요. 아래는 이전 결과입니다.</p>':''}${s.syncError?'<p class="warning">최근 동기화 실패: '+esc(s.syncError)+'</p>':''}<div class="counts">대상 ${s.eligibleCount}명 · 응답 ${s.answered.length}명 · 미응답 ${s.missing.length}명</div>${s.scores?`<details class="question-chart"><summary>만족도 점수 · 분포</summary>${scoreChart(s)}</details>`:""}${list(s,'missing','미응답')}${list(s,'answered','응답 완료')}${list(s,'review','확인 필요')}${teacherClass?'':list(s,'excluded','출석 기준 제외')+list(s,'unknown','명단 불일치')}<small>중복 제출 ${s.duplicateCount}건 제외${s.invalidCount?' · 반/이름 확인 불가 '+s.invalidCount+'건':''}</small>`:'<p class="pending">아직 대조하지 않았습니다. 미응답 0명이라는 뜻이 아닙니다.</p>'}${owner?`<div class="actions"><button data-sync="${e.id}" ${reader.connected()&&r.date<=todayKST()?'':'disabled'}>이 설문 동기화</button><button data-config="${e.id}">응답 연결 확인</button></div><small>${r.source?esc(r.source.title):'응답 시트를 하나로 연결하지 못했습니다.'}</small>`:''}</section>`;}).join('')||(classLoading?'<p>선택한 반의 설문을 불러오는 중…</p>':'<p>선택한 기간에 등록된 설문이 없습니다.</p>')}</div>`;
  if(compact){const summaries=shown.map(e=>results[e.id]).filter(Boolean),eligible=summaries.reduce((n,s)=>n+s.eligibleCount,0),answered=summaries.reduce((n,s)=>n+s.answered.length,0);content.innerHTML=`<h2>만족도조사 현황</h2>${cards([['응답률',pct(eligible?answered/eligible*100:null),answered+' / '+eligible+'건'],['미응답',summaries.reduce((n,s)=>n+s.missing.length,0)+'건','설문별 미응답 합계'],['대조 완료',summaries.length+'개','오늘까지 설문 '+shown.length+'개']])}<button id="surveyMore">설문별 미응답 · 전체 현황 →</button>`;$('#surveyMore').onclick=()=>onMore?.();return;}
  $('#surveyCharts').onclick=async()=>{content.hidden=true;const panel=document.createElement('section');root.append(panel);try{const mod=await import('./survey-statistics.mjs');chartWork=await mod.mountSurveyStatistics(panel,{db,user,classes,teacherClass,onBack(){chartWork?.dispose();panel.remove();content.hidden=false;}});}catch(e){panel.textContent=e.message;content.hidden=false;}};
  $('#surveyFilter').onchange=e=>{filter=e.target.value;render();};if($('#surveyClass'))$('#surveyClass').onchange=e=>{selected=e.target.value;void loadClass();};$('#surveyRefresh').onclick=()=>void loadClass();
  if(owner){$('#surveyConnect').onclick=()=>run(async()=>{await reader.connect();notice='응답 시트 연결 완료. 선택한 반의 응답을 동기화합니다.';await syncClass();});$('#surveySync').onclick=()=>run(syncClass);$('#surveyAll').onclick=()=>run(async()=>{const original=selected;try{for(const c of classes){if(disposed)break;selected=String(c.id);await loadClass(false);await syncClass();}}finally{selected=original;await loadClass(false);}});root.querySelectorAll('[data-sync]').forEach(b=>b.onclick=()=>run(()=>syncClass(b.dataset.sync)));root.querySelectorAll('[data-config]').forEach(b=>b.onclick=()=>configure(events().find(e=>e.id===b.dataset.config)));}
  if(busy||classLoading)root.querySelectorAll('button,select').forEach(b=>b.disabled=true);
 }
 async function loadClass(clear=true){const n=++epoch,cid=selected;classLoading=true;if(clear){error='';notice='설문 저장 결과를 읽는 중…';}render();try{const [tt,s]=await Promise.all([within(timetables.read('published',cid),15000),store.read(cid)]);if(n!==epoch||disposed)return;entries=tt?.entries||[];results=s;if(clear)notice='저장 결과를 불러왔습니다.';}catch(e){if(n!==epoch)return;entries=[];results={};error='조회 실패 · '+e.message;}finally{if(n===epoch){classLoading=false;render();}}}
 async function run(fn){if(busy||classLoading)return;busy=true;error='';render();try{await fn();}catch(e){error=e.message;}finally{busy=false;render();}}
 async function syncClass(onlyId){
  const cid=selected,eligibleEvents=events().filter(e=>(!onlyId||e.id===onlyId)&&resolved(e).date<=todayKST());if(!eligibleEvents.length){notice='동기화할 설문이 없습니다.';return;}
  const sheet=await readJson('/api/attendance-reader',{classId:cid,idToken:await within(user.getIdToken()),allowCache:true},{timeout:55000});
  const derived=await syncAttendanceSummary(db,user,cid,sheet);const failures=[];let done=0;
  for(const e of eligibleEvents){if(disposed)return;const r=resolved(e);try{if(!e.scheduleMatched&&!config.events?.[e.id]?.date)throw Error('시간표 강의 또는 교육일 연결 확인 필요');if(!r.source)throw Error('응답 시트 연결 확인 필요');
    const responses=await reader.responses(r.source.sheetUrl),targets=targetsFromDerived(derived,r.date),summary=summarizeResponses({classId:cid,targets,responses});
    const scores=summarizeScores(responses,cid,summary.answered,{scale:Number(config.events?.[e.id]?.scale||5)});const data={...summary,scores,attendanceFingerprint:derived.fingerprint,title:e.title,date:r.date,sourceId:r.source.id,url:r.url,syncedAt:new Date().toISOString(),scheduleFingerprint:JSON.stringify(entries.filter(x=>e.lessonIds.includes(x.id)).map(x=>[x.id,x.date,x.title,x.day]))};await store.save(cid,e.id,data);results[e.id]=data;done++;
   }catch(err){failures.push(e.title+': '+err.message);}notice=`${cid}반 · ${done}/${eligibleEvents.length}개 설문 동기화${failures.length?' · 확인 필요 '+failures.length+'건':''}`;render();
  }
  if(failures.length)error=failures.join('\n');
 }
 function configure(e){const r=resolved(e),dialog=$('#surveyDialog');dialog.innerHTML=`<h3>${esc(e.title)} · 응답 연결</h3><p>대조에 쓸 교육일과 응답 원본을 확인합니다. 원본에는 쓰지 않습니다.</p><label>교육일<input id="surveyDate" type="date" value="${r.date}"></label><label>설문 참여 링크<input id="surveyUrl" type="url" value="${esc(r.url)}"></label><label>응답 시트<select id="surveySource"><option value="">연결 확인 필요</option>${catalog.responseSources.map(s=>`<option value="${s.id}" ${r.source?.id===s.id?'selected':''}>${esc(s.title)}</option>`).join('')}</select></label><label>만족도 척도<select id="surveyScale">${[5,7,10].map(n=>`<option value="${n}" ${Number(config.events?.[e.id]?.scale||5)===n?"selected":""}>${n}점</option>`).join("")}</select></label><p id="configError"></p><button id="configCancel">닫기</button><button id="configSave">연결 저장</button>`;$('#configCancel').onclick=()=>dialog.close();$('#configSave').onclick=async()=>{const b=$('#configSave');b.disabled=true;try{const value={date:$('#surveyDate').value,url:validLink($('#surveyUrl').value),sourceId:$('#surveySource').value,scale:Number($('#surveyScale').value)};if(!value.date||!value.sourceId)throw Error('교육일과 응답 시트를 선택해 주세요.');await store.saveConfig(e.id,value);config.events??={};config.events[e.id]=value;dialog.close();render();}catch(err){$('#configError').textContent=err.message;}finally{b.disabled=false;}};dialog.showModal();}
 const timer=setInterval(()=>{if(disposed||busy||document.hidden||!host.isConnected||!host.getClientRects().length)return;if(owner&&reader.connected())void run(syncClass);else void loadClass(false);},600000);
 try{const r=await fetch('/survey-catalog.json');if(!r.ok)throw Error('설문 기준을 불러오지 못했습니다.');catalog=await r.json();config=await store.configuration();await loadClass();}catch(e){content.textContent=e.message;}
 return {canLeave:()=>!busy,dispose(){disposed=true;epoch++;clearInterval(timer);reader.clear();chartWork?.dispose();}};
}
