import {readMaterials,materialUrl} from './lecture-materials.mjs';
import {createSurveyStore} from './survey-store.mjs';
import {timetableImpact,timetableImpactHtml} from './timetable-impact.mjs';
import {loadSurveyLinks,surveyLink} from './survey-links.mjs';
import {shiftForHoliday} from './timetable-holiday.mjs';
import {createTimetableBoard,moveLesson} from './timetable-board.mjs';
import {todayKST,weekDays,monthDays,sortEntries,validateEntry,conflicts,publishEntries,visibleToday,lectureEndDays,lectureEndsOn} from './timetable-core.mjs';
import {createTimetableStore} from './timetable-store.mjs';
import {curriculumPlan,correctedSeed} from './timetable-reference.mjs';
import {swapLesson,neighbour,conflictMap,classProgress,progressText,hideWeekend,bulkAssign,copyPeriod,recentChanges,toIcs} from './timetable-tools.mjs';
import {mergeSeed,draftSeedVersion} from './timetable-sync.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const palette={'동기부여':['#8864bb','#f4effb'],'디지털스킬':['#326ac0','#edf3fc'],'소프트스킬':['#4291a4','#edf7f9'],'직무특화':['#28685e','#ecf6f1'],'공장견학':['#b67726','#fff5e7'],'문화체험':['#bc5b80','#fceff4'],'진로탐색':['#5d67aa','#f0f0fc'],'현직자특강':['#be713a','#fff2e9'],'분해조립':['#548752','#f0f7ec'],'실차체험':['#548752','#f0f7ec'],'공통행사':['#a26148','#faf0ec'],'휴일':['#82909f','#f1f3f6']};
const paint=m=>{const c=palette[m]||['#65748b','#f0f4f8'];return `--module:${c[0]};--tint:${c[1]}`;};
const option=(value,selected,label=value)=>`<option value="${esc(value)}" ${value===selected?'selected':''}>${esc(label)}</option>`;
const weekday=d=>new Intl.DateTimeFormat('ko-KR',{weekday:'short',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
const id=()=>crypto.randomUUID();
function lesson(e,instructors={},click=false,cid='',ending=false,extra={}){
 const name=e.instructorName||instructors[e.instructorId]?.name||'',time=e.start?`${e.start}–${e.end}`:e.hours?`${e.hours}시간 · 시각 미등록`:'';
 return `<div class="lesson-container"><${click?'button':'article'} class="lesson" style="${paint(e.module)}" ${click?`draggable="${e.kind!=='holiday'}" data-edit="${esc(e.id)}" data-cid="${esc(cid)}" aria-label="${esc(cid+'반 '+e.date+' '+e.title+' 수정')}"`:''}>${extra.changed?`<small class="changed-badge">${esc(extra.changed)}</small>`:''}<small>${esc(e.module)}${e.online?' · 비대면':''}</small><strong>${esc(e.title)}${e.day?' · '+e.day+'일차':''}</strong><small>${esc(time)}</small>${e.kind==='holiday'?'':`<small>${esc(name||'강사 미등록')}${e.venue?' · '+esc(e.venue):''}</small>`}${e.note?`<small>${esc(e.note)}</small>`:''}${extra.warn?`<small class="warn" title="${esc(extra.warn)}">⚠ ${esc(extra.warn)}</small>`:''}</${click?'button':'article'}>${(e.materials||[]).map(m=>`<a class="lecture-end" target="_blank" rel="noopener" href="${esc(materialUrl(m.url))}">자료 · ${esc(m.title)} ↗</a>`).join('')}${ending?`<a class="lecture-end survey-lesson-link" href="${esc(surveyLink(cid,e))}" target="_blank" rel="noopener">모듈 종료일, 만족도조사 필요 ↗</a>`:''}</div>`;
}
function shell(host){const root=host.shadowRoot||host.attachShadow({mode:'open'});root.innerHTML='<link rel="stylesheet" href="/timetable.css?v=20260929-1"><div id="content"></div><dialog id="editor"></dialog>';return root;}
export async function mountTimetableAdmin(host,{db,user,classes}){
 const root=shell(host),store=createTimetableStore(db,user),surveys=createSurveyStore(db,user),$=s=>root.querySelector(s),content=$('#content');
 let surveyCatalog={events:[]},seed,reference,catalog,drafts={},published={},instructors={},selected='all',date=todayKST(),mode='schedule',busy=false,message='',error=false,view='week',pending={},undo=[],disposed=false,planCache=null,showWeekend=false,warnings=new Map(),seedBases={};
 const meta=cid=>classes.find(c=>String(c.id)===String(cid))||{id:cid};
 content.innerHTML='<div class="empty">시간표와 강사 정보를 불러오는 중…</div>';
 async function load(fresh=false){planCache=null;surveyCatalog=await loadSurveyLinks()||{events:[]};const r=await fetch('/timetable-seed.json',{cache:'no-cache'});if(!r.ok)throw Error('기준 엑셀 일정을 읽지 못했습니다.');seed=await r.json();const rr=await fetch('/timetable-reference.json');if(!rr.ok)throw Error('교육과정 기준을 읽지 못했습니다.');reference=await rr.json();seed=correctedSeed(seed,reference);for(const c of Object.values(seed.classes))c.seedVersion=seed.version;[catalog,drafts,published,instructors]=await Promise.all([store.catalog(seed,{fresh}),store.all('draft',{fresh}),store.all('published',{fresh}),store.all('instructors',{fresh})]);
  // Earlier workbook versions let an Excel update tell sheet changes apart from portal edits.
  for(const v of new Set(Object.values(drafts).map(draftSeedVersion)))if(v!==seed.version&&!(v in seedBases)){try{const b=await fetch(`/timetable-seeds/${encodeURIComponent(v)}.json`);seedBases[v]=b.ok?correctedSeed(await b.json(),reference):null;}catch{seedBases[v]=null;}}
 }
 const plan=()=>planCache||(planCache=curriculumPlan(catalog,drafts,published,reference));
 const data=cid=>pending[cid]||drafts[cid]||seed.classes[cid]||{entries:[],revision:0};
 const combined=()=>Object.fromEntries(classes.map(c=>[c.id,data(c.id)]));
 const dirty=()=>Object.keys(pending);
 async function showImpact(target,changes,{operation='draft',note=''}={}){
  const ticket=Symbol();target.impactTicket=ticket;target.innerHTML='<p class="muted">시간표 변경 영향을 확인하는 중…</p>';
  let config={},configKnown=true;try{config=await surveys.configuration();}catch{configKnown=false;}
  if(disposed||!target.isConnected||target.impactTicket!==ticket)return false;
  const impacts=changes.map(c=>timetableImpact({classId:c.classId,before:operation==='publish'?published[c.classId]?.entries||[]:drafts[c.classId]?.entries||seed.classes[c.classId]?.entries||[],after:c.entries,published:published[c.classId]?.entries||[],publicAfter:publishEntries(c.entries,instructors),catalog:surveyCatalog,config,configKnown}));
  target.innerHTML=timetableImpactHtml(impacts,{operation,note});return true;
 }
 function reviewPublish(targets){
  const dialog=$('#editor'),changes=targets.map(c=>({classId:String(c.id),entries:publishEntries(drafts[c.id].entries,instructors)}));
  dialog.innerHTML='<h3>담임에게 공개할 시간표 확인</h3><div id="publishImpact"></div><div class="actions"><button id="publishCancel">취소</button><button id="publishConfirm" class="primary" disabled>공개 확정</button></div>';
  const confirmButton=$('#publishConfirm');$('#publishCancel').onclick=()=>dialog.close();dialog.showModal();
  void showImpact($('#publishImpact'),changes,{operation:'publish'}).then(shown=>{if(shown)confirmButton.disabled=false;});
  confirmButton.onclick=()=>{confirmButton.disabled=true;dialog.close();void action(async()=>{let count=0;for(const c of changes){const old=published[c.classId],recent=old?recentChanges(old.entries||[],c.entries,old.recentChanges||[]):[];published[c.classId]=await store.publish(c.classId,drafts[c.classId],old?.revision||0,c.entries,{recentChanges:recent});message=`${++count}/${changes.length}개 반 공개 완료`;}});};
 }

 function applyPending(cid,entries,text){undo.push(structuredClone(pending));if(undo.length>10)undo.shift();pending={...pending,[cid]:{...data(cid),entries}};message=`${cid}반 · ${text}. 시간표 저장을 눌러 확정해 주세요.`;error=false;render();}
 const shifted=(before,after,skip)=>{const old=new Map(before.map(e=>[e.id,e.date]));return new Set(after.filter(e=>e.id!==skip&&old.get(e.id)!==e.date).map(e=>e.id));};
 function chooseMove(cid,id,date,swapId){
  const base=data(cid).entries,inserted=moveLesson(base,id,date,swapId),moved=shifted(base,inserted,id);
  if(inserted===base)return;if(!moved.size)return applyPending(cid,inserted,'수업 날짜를 옮겼습니다');
  const source=base.find(e=>e.id===id),target=base.find(e=>e.id===swapId)||sortEntries(base).find(e=>e.date===date&&e.kind!=='holiday'&&e.id!==id),dialog=$('#editor');
  dialog.innerHTML=`<h3>${esc(cid)}반 · 수업을 어떻게 옮길까요?</h3><p><b>${esc(source.title)}</b> (${esc(source.date)}) → ${esc(date)}${target?` · <b>${esc(target.title)}</b> 자리`:''}</p><div class="choice-list"><button id="moveInsert" class="primary">끼워넣기<small>사이 수업 ${moved.size}개가 한 칸씩 순서대로 밀립니다</small></button>${target?`<button id="moveSwap">맞바꾸기<small>두 수업의 날짜만 서로 바꿉니다 · 다른 수업은 그대로</small></button>`:''}<button id="moveCancel">취소</button></div>`;
  $('#moveCancel').onclick=()=>dialog.close();
  $('#moveInsert').onclick=()=>{dialog.close();applyPending(cid,inserted,'수업을 끼워 넣고 사이 일정을 순서대로 옮겼습니다');};
  if(target)$('#moveSwap').onclick=()=>{try{const next=swapLesson(base,id,target.id);dialog.close();applyPending(cid,next,'두 수업의 날짜를 맞바꿨습니다');}catch(e){dialog.close();message=e.message;error=true;render();}};
  dialog.showModal();
 }
 const board=createTimetableBoard({root,classes,data,lesson,instructors:()=>instructors,status:cid=>pending[cid]?'<span class="dirty">저장 전 이동</span>':!drafts[cid]?'<span class="dirty">엑셀 미저장</span>':published[cid]?.sourceRevision===drafts[cid]?.revision?'✓ 공개됨':'<span class="dirty">공개 전 변경</span>',warning:(cid,id)=>warnings.get(cid+'|'+id)||'',progress:cid=>progressText(classProgress(data(cid).entries||[])),weekend:()=>showWeekend,preview:(cid,id,date,swapId)=>{const base=data(cid).entries;return shifted(base,moveLesson(base,id,date,swapId),id);},onError:text=>{message=text;error=true;render();},onMove(cid,id,date,swapId){if(busy)return;chooseMove(cid,id,date,swapId);}});
 const leave=()=>!busy&&(!dirty().length||confirm('저장하지 않은 시간표 이동이 있습니다. 저장하지 않고 나갈까요?'));
 const beforeUnload=e=>{if(dirty().length){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',beforeUnload);
 async function saveBoard(){if(!dirty().length)return;await action(async()=>{const changes=dirty().map(classId=>({classId,entries:data(classId).entries,seedVersion:data(classId).seedVersion,revision:drafts[classId]?.revision||0}));const warnings=changes.flatMap(c=>c.entries.flatMap(e=>conflicts(e,combined(),c.classId)));if(warnings.length&&!confirm(`강사 일정 중복 또는 시각 확인이 필요한 항목이 ${warnings.length}건 있습니다. 그래도 시간표를 저장할까요?`)){message='이동한 시간표를 유지했습니다. 강사 일정을 확인해 주세요.';return;}const saved=await store.saveDrafts(changes);drafts={...drafts,...saved};pending={};undo=[];planCache=null;message='시간표 저장 완료 · 확인 후 담임에게 공개해 주세요.';});}
 root.addEventListener('click',e=>{if(busy)return;const edit=e.target.closest?.('[data-edit]'),add=e.target.closest?.('[data-add]');if(edit)editEntry(edit.dataset.cid,data(edit.dataset.cid).entries.find(x=>x.id===edit.dataset.edit));else if(add)editEntry(add.dataset.cid,null,add.dataset.add);});
 async function action(fn){if(busy||disposed)return;busy=true;message='처리 중…';error=false;render();try{await fn();}catch(e){message=e.message;error=true;}finally{busy=false;planCache=null;if(host.isConnected&&!disposed)render();}}
 function render(){
  if(disposed||!host.isConnected)return;const shown=selected==='all'?classes:classes.filter(c=>String(c.id)===selected);warnings=conflictMap(combined(),instructors);const outdated=syncTargets();
  content.innerHTML=`<div class="top"><div><div class="eyebrow">HINT / TIMETABLE</div><h2>시간표 관리</h2><div class="muted">수업 날짜는 일정표 기준, 공장·교육과정은 운영 시트 기준입니다. 강사 연락처는 관리자만 확인합니다.</div></div><div class="actions"><button id="reload">↻ 새로고침</button><button id="import">엑셀 기준 17개 반 가져오기</button>${plan().changes.length?'<button id="referenceApply" class="primary">시트 기준 분류 반영</button>':''}</div></div>${outdated.length?`<div class="sync-banner"><div><b>새 엑셀 일정표가 올라왔습니다</b><span>${esc(seed.source)} · 버전 ${esc(seed.version)} · 편집본이 있는 ${outdated.length}개 반에 반영 전입니다. 강사·시각·전달사항은 유지하고, 엑셀에서 바뀐 수업만 고칩니다.</span></div><button id="syncReview" class="primary">엑셀 변경분 검토</button></div>`:''}<div class="toolbar switch">${[['schedule','반별 시간표'],['catalog','과정·강의 관리'],['instructors','강사 관리'],['preview','담임 화면 미리보기']].map(([v,t])=>`<button data-mode="${v}" class="${mode===v?'active':''}">${t}</button>`).join('')}</div>${message?`<div role="status" class="message ${error?'error':''}">${esc(message)}</div>`:''}<div id="body"></div>`;
  const body=$('#body');
  if(mode==='schedule'){
   body.innerHTML=`<div class="board-toolbar"><div class="toolbar nav-row"><label>반<select id="classFilter">${option('all',selected,'전체 17개 반')}${classes.map(c=>option(String(c.id),selected,`${c.id}반 · ${c.course}`)).join('')}</select></label><div class="switch view-switch">${[['week','주간'],['month','월간'],['all','전체 일정']].map(([v,t])=>`<button data-period="${v}" class="${view===v?'active':''}">${t}</button>`).join('')}</div><div class="date-nav"><button id="previous" aria-label="이전 기간" ${view==='all'?'disabled':''}>‹</button><label>기준 날짜<input id="date" type="date" value="${date}"></label><button id="next" aria-label="다음 기간" ${view==='all'?'disabled':''}>›</button><button id="today">오늘</button></div><label class="inline-check"><input id="weekendToggle" type="checkbox" ${showWeekend?'checked':''}> 주말 표시</label></div><div class="toolbar action-row"><div class="action-group"><button id="new">+ 일정 추가</button><button id="bulk">일괄 작업</button><button id="holidayShift">대체휴일 · 일정 순연</button></div><div class="action-group"><button id="undoMove" ${undo.length?'':'disabled'}>이동 되돌리기</button><button class="primary" id="saveTimetable" ${dirty().length?'':'disabled'}>시간표 저장${dirty().length?' ('+dirty().length+'개 반)':''}</button><button id="publish" ${dirty().length?'disabled':''}>${selected==='all'?'17개 반':'선택 반'} 담임에게 공개</button></div></div></div><p class="muted move-guide">수업을 끌어 빈 날짜에 놓으면 이동 · 다른 수업 위에 놓으면 끼워넣기/맞바꾸기 선택 · 밀려날 수업은 끄는 동안 점선으로 표시 · 휴대폰에서는 수업을 눌러 앞뒤 수업과 순서 바꾸기 · ⚠ 강사 일정 겹침${warnings.size?` <b class="warn-count">⚠ 겹침 ${warnings.size}건</b>`:''}</p>${dirty().length?'<div id="boardImpact"></div>':''}${shown.flatMap(c=>lectureEndsOn(data(c.id).entries,date).map(e=>`<div class="lecture-end notice">${esc(c.id)}반 · ${esc(e.title)} — <a href="${esc(surveyLink(c.id,e))}" target="_blank" rel="noopener">모듈 종료일, 만족도조사 필요 ↗</a></div>`)).join('')}<div class="legend">${catalog.modules.map(m=>`<span style="${paint(m)}">${esc(m)}</span>`).join('')}</div>${board.html({shown,view,date})}`;
   if(dirty().length){const button=$('#saveTimetable');button.disabled=true;void showImpact($('#boardImpact'),dirty().map(classId=>({classId,entries:data(classId).entries}))).then(shown=>{if(shown&&!busy)button.disabled=false;});}
   root.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{view=b.dataset.period;render();});$('#holidayShift').onclick=holidayDialog;$('#bulk').onclick=()=>bulkDialog();$('#weekendToggle').onchange=e=>{showWeekend=e.target.checked;render();};$('#saveTimetable').onclick=saveBoard;$('#undoMove').onclick=()=>{if(undo.length){pending=undo.pop();message='이전 이동 상태로 되돌렸습니다.';error=false;render();}};
   $('#classFilter').onchange=e=>{selected=e.target.value;render();};$('#date').onchange=e=>{if(e.target.value&&e.target.value!==date){date=e.target.value;render();}};$('#today').onclick=()=>{date=todayKST();render();};
   for(const [key,delta] of [['previous',-1],['next',1]])$('#'+key).onclick=()=>{const d=new Date(date+'T12:00:00Z');if(view==='month'){d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+delta);}else d.setUTCDate(d.getUTCDate()+7*delta);date=d.toISOString().slice(0,10);render();};
   $('#new').onclick=()=>editEntry(selected==='all'?null:selected,null,date);
   $('#publish').onclick=()=>{const targets=shown.filter(c=>drafts[c.id]);if(!targets.length){message='먼저 엑셀 기준 일정을 가져오거나 편집본을 저장해 주세요.';render();return;}reviewPublish(targets);};
  }else if(mode==='catalog')renderCatalog(body);
  else if(mode==='instructors')renderInstructors(body);
  else {const cid=selected==='all'?'1':selected;body.innerHTML=`<div class="toolbar"><label>미리볼 반<select id="previewClass">${classes.map(c=>option(String(c.id),cid,`${c.id}반 · ${c.course}`)).join('')}</select></label><span class="muted">담임에게 공개한 일정만 표시합니다.</span></div><div id="preview"></div>`;$('#previewClass').onchange=e=>{selected=e.target.value;render();};renderTeacher($('#preview'),published[cid]?.entries||[],meta(cid),{changes:published[cid]?.recentChanges||[]});}
  root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render();});
  if($('#referenceApply'))$('#referenceApply').onclick=reviewReference;if($('#syncReview'))$('#syncReview').onclick=reviewSeedSync;
  $('#reload').onclick=()=>{if(dirty().length&&!confirm('저장 전 이동을 버리고 최신 시간표를 다시 읽을까요?'))return;return action(async()=>{await load(true);pending={};undo=[];message='최신 시간표를 읽었습니다.';});};
  $('#import').onclick=()=>{const targets=classes.filter(c=>!drafts[c.id]);if(!targets.length){message='17개 반의 편집본이 이미 있습니다. 기존 일정은 유지됩니다.';render();return;}if(!confirm(`편집본이 없는 ${targets.length}개 반에 엑셀 일정을 가져올까요? 기존 편집본과 원본 엑셀은 유지됩니다.`))return;action(async()=>{let n=0;for(const c of targets){drafts[c.id]=await store.save('draft',c.id,{classId:String(c.id),entries:seed.classes[c.id].entries,seedVersion:seed.version},0);message=`${++n}/${targets.length}개 반 가져오기 완료 · 확인 후 담임에게 공개해 주세요.`;}});};
  if(busy)root.querySelectorAll('button,input,select').forEach(b=>b.disabled=true);
 }
 const syncTargets=()=>classes.filter(c=>drafts[c.id]&&draftSeedVersion(data(c.id))!==seed.version).map(c=>String(c.id));
 function reviewSeedSync(){
  const plans=syncTargets().map(cid=>{const d=data(cid),v=draftSeedVersion(d),base=seedBases[v]?.classes?.[cid]?.entries||null;return {...mergeSeed({classId:cid,base,next:seed.classes[cid]?.entries||[],draft:d.entries,version:seed.version}),from:v,baseKnown:!!base};});
  const changed=plans.filter(p=>p.changes.length),dialog=$('#editor'),row=c=>`<tr class="${c.conflict?'conflict':''}"><td>${esc(c.kind)}</td><td>${esc(c.title)}${c.day?' · '+c.day+'일차':''}${c.conflict?'<br><small>포털에서 바꾼 값을 엑셀 값으로 덮어씁니다</small>':''}</td><td>${esc(c.from)}</td><td>${esc(c.to)}</td><td>${esc(c.fields.join(', '))}</td></tr>`;
  dialog.innerHTML=`<h3>엑셀 일정표 변경분 검토</h3><p class="muted">${esc(seed.source)} · 버전 ${esc(seed.version)}. 엑셀에서 바뀐 수업만 편집본에 반영합니다. 강사·시각·장소·전달사항과, 엑셀이 바꾸지 않은 포털 이동은 그대로 둡니다. 적용 후 시간표 저장 → 담임에게 공개 순서로 확정됩니다.</p>${plans.some(p=>!p.baseKnown)?'<p class="dirty">일부 반은 이전 엑셀 버전을 찾지 못해 포털 수정과 엑셀 변경을 구분할 수 없습니다. 해당 반은 날짜·강의가 엑셀 값으로 맞춰집니다.</p>':''}${changed.length?changed.map(p=>`<details ${changed.length<=3?'open':''}><summary><label class="inline-check"><input type="checkbox" data-sync="${esc(p.classId)}" checked> ${esc(p.classId)}반 · 변경 ${p.changes.length}건${p.changes.some(c=>c.conflict)?` · <span class="dirty">포털 수정과 겹침 ${p.changes.filter(c=>c.conflict).length}건</span>`:''}${p.skipped.length?` · 포털에서 삭제한 ${p.skipped.length}건 유지`:''}</label></summary><div class="table-scroll"><table class="sync-table"><thead><tr><th>구분</th><th>수업</th><th>기존</th><th>엑셀</th><th>바뀐 항목</th></tr></thead><tbody>${p.changes.map(row).join('')}</tbody></table></div></details>`).join(''):'<p>편집본과 엑셀 사이에 바뀐 수업이 없습니다. 버전 표시만 갱신합니다.</p>'}${plans.length-changed.length?`<p class="muted">변경 없는 ${plans.length-changed.length}개 반은 버전 표시만 갱신합니다.</p>`:''}<div id="syncImpact"></div><div class="actions"><button id="syncCancel">취소</button><button id="syncApply" class="primary">선택한 반에 적용</button></div>`;
  $('#syncCancel').onclick=()=>dialog.close();
  if(changed.length)void showImpact($('#syncImpact'),changed.map(p=>({classId:p.classId,entries:p.entries})),{note:'적용은 화면의 편집본만 바꿉니다. 시간표 저장 후 공개해야 담임에게 반영됩니다.'});
  $('#syncApply').onclick=()=>{const off=new Set([...root.querySelectorAll('[data-sync]')].filter(x=>!x.checked).map(x=>x.dataset.sync)),chosen=plans.filter(p=>!off.has(p.classId));if(!chosen.length){dialog.close();return;}
   undo.push(structuredClone(pending));if(undo.length>10)undo.shift();for(const p of chosen)pending[p.classId]={...data(p.classId),entries:p.entries,seedVersion:seed.version};
   message=`엑셀 변경분을 ${chosen.length}개 반 편집본에 적용했습니다 (${chosen.reduce((n,p)=>n+p.changes.length,0)}건). 시간표 저장을 눌러 확정한 뒤 담임에게 공개해 주세요.`;error=false;dialog.close();render();};
  dialog.showModal();
 }
 function bulkDialog(kind='assign'){
  const dialog=$('#editor'),week=weekDays(date),from=week[0],to=week[4],courseOf=cid=>meta(cid).course||'',courses=[...new Set(classes.map(c=>courseOf(c.id)))];
  const classBoxes=(name,checked)=>`<div class="class-picks">${classes.map(c=>`<label class="inline-check"><input type="checkbox" name="${name}" value="${esc(c.id)}" ${checked(String(c.id))?'checked':''}> ${esc(c.id)}반</label>`).join('')}</div><div class="quick-picks"><button type="button" data-pick="all">전체</button><button type="button" data-pick="none">해제</button>${courses.map(c=>`<button type="button" data-pick="${esc(c)}">${esc(c)}</button>`).join('')}</div>`;
  const current=selected==='all'?'':selected;
  dialog.innerHTML=`<h3>일괄 작업</h3><div class="switch view-switch"><button type="button" data-bulk="assign" class="${kind==='assign'?'active':''}">강사·장소·시간 지정</button><button type="button" data-bulk="copy" class="${kind==='copy'?'active':''}">다른 반으로 기간 복사</button></div><form id="bulkForm">${kind==='assign'?`<p class="muted">선택한 반에서 조건에 맞는 수업에 한꺼번에 적용합니다. 비워 둔 항목은 바꾸지 않습니다.</p><fieldset><legend>적용 반</legend>${classBoxes('classes',cid=>!current||cid===current)}</fieldset><div class="form-grid"><label class="full">강의<select name="title"></select></label><label>시작일 (선택)<input name="from" type="date"></label><label>종료일 (선택)<input name="to" type="date"></label><label>강사<select name="instructorId">${option('','','바꾸지 않음')}${option('__none','','미등록으로 비우기')}${Object.entries(instructors).map(([k,v])=>option(k,'',v.name)).join('')}</select></label><label>장소<input name="venue" maxlength="200" placeholder="바꾸지 않음"></label><label>시작 시각<input name="start" type="time"></label><label>종료 시각<input name="end" type="time"></label><label>방식<select name="online">${option('','','바꾸지 않음')}${option('false','','대면')}${option('true','','비대면')}</select></label></div>`:`<p class="muted">원본 반의 기간 수업을 대상 반에 복사합니다. 휴일은 복사하지 않고, 강사·시각·전달사항은 함께 복사합니다.</p><div class="form-grid"><label>원본 반<select name="source">${classes.map(c=>option(String(c.id),current||String(classes[0].id),`${c.id}반 · ${c.course}`)).join('')}</select></label><label>방식<select name="mode">${option('replace','replace','대상 반의 같은 기간 수업을 교체')}${option('add','','추가만 (기존 수업 유지)')}</select></label><label>시작일<input name="from" type="date" value="${from}" required></label><label>종료일<input name="to" type="date" value="${to}" required></label></div><fieldset><legend>대상 반</legend>${classBoxes('targets',()=>false)}</fieldset>`}<div id="bulkResult" class="muted"></div><div id="bulkImpact"></div><p id="formError" role="alert"></p><div class="actions"><button type="button" id="cancel">취소</button><button type="button" id="bulkPreview">미리보기</button><button type="submit" class="primary" disabled>편집본에 적용</button></div></form>`;
  const f=$('#bulkForm'),apply=f.querySelector('[type="submit"]'),picked=name=>[...f.querySelectorAll(`[name="${name}"]:checked`)].map(x=>x.value);let plans=[];
  const reset=()=>{plans=[];apply.disabled=true;$('#bulkResult').textContent='';$('#bulkImpact').impactTicket=Symbol();$('#bulkImpact').textContent='';};
  function titles(){if(kind!=='assign')return;const list=[...new Set(picked('classes').flatMap(cid=>data(cid).entries.filter(e=>e.kind!=='holiday').map(e=>e.title)))].sort((a,b)=>a.localeCompare(b,'ko'));const was=f.elements.title.value;f.elements.title.innerHTML=option('',was,'모든 수업 (기간 조건만)')+list.map(t=>option(t,was)).join('');}
  function sameCourse(){if(kind!=='copy')return;const src=f.elements.source.value;f.querySelectorAll('[name="targets"]').forEach(x=>{x.checked=x.value!==src&&courseOf(x.value)===courseOf(src);x.disabled=x.value===src;});}
  titles();sameCourse();
  dialog.querySelectorAll('[data-bulk]').forEach(b=>b.onclick=()=>bulkDialog(b.dataset.bulk));$('#cancel').onclick=()=>dialog.close();
  f.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{const v=b.dataset.pick,box=b.closest('fieldset');box.querySelectorAll('input[type=checkbox]:not(:disabled)').forEach(x=>x.checked=v==='all'||v!=='none'&&courseOf(x.value)===v);titles();reset();});
  f.addEventListener('change',e=>{if(e.target.name==='classes')titles();if(e.target.name==='source')sameCourse();reset();});f.addEventListener('input',reset);
  function compute(){
   const v=Object.fromEntries(new FormData(f));
   if(kind==='assign'){
    const classIds=picked('classes');if(!classIds.length)throw Error('적용할 반을 선택해 주세요.');
    const patch={};if(v.instructorId)patch.instructorId=v.instructorId==='__none'?'':v.instructorId;if(v.venue.trim())patch.venue=v.venue.trim();if(v.start||v.end){if(!v.start||!v.end)throw Error('시작·종료 시각을 함께 입력해 주세요.');patch.start=v.start;patch.end=v.end;}if(v.online)patch.online=v.online==='true';
    if(!Object.keys(patch).length)throw Error('바꿀 항목(강사·장소·시각·방식)을 하나 이상 입력해 주세요.');if(!v.title&&!v.from&&!v.to)throw Error('강의나 기간 중 하나는 지정해 주세요. 전체 일정 일괄 변경을 막기 위한 확인입니다.');
    return classIds.map(cid=>({classId:cid,...bulkAssign(data(cid).entries,{title:v.title,from:v.from,to:v.to,patch})})).filter(p=>p.count);
   }
   const targets=picked('targets').filter(t=>t!==v.source);if(!targets.length)throw Error('복사할 대상 반을 선택해 주세요.');
   return targets.map(cid=>{const r=copyPeriod(data(v.source).entries,data(cid).entries,{from:v.from,to:v.to,replace:v.mode==='replace',course:courseOf(cid).startsWith('제조')?'제조지능화':courseOf(cid),lectures:catalog.lectures,makeId:id});return {classId:cid,entries:r.entries,count:r.added,removed:r.removed};});
  }
  $('#bulkPreview').onclick=()=>{reset();$('#formError').textContent='';try{plans=compute();if(!plans.length)throw Error('조건에 맞는 수업이 없습니다.');$('#bulkResult').innerHTML=plans.map(p=>`<div>${esc(p.classId)}반 · ${kind==='assign'?`수업 ${p.count}건 변경`:`${p.count}건 복사${p.removed?` · 기존 ${p.removed}건 교체`:''}`}</div>`).join('');void showImpact($('#bulkImpact'),plans).then(shown=>{if(shown)apply.disabled=false;});}catch(err){$('#formError').textContent=err.message;}};
  f.onsubmit=ev=>{ev.preventDefault();if(!plans.length)return;undo.push(structuredClone(pending));if(undo.length>10)undo.shift();for(const p of plans)pending[p.classId]={...data(p.classId),entries:p.entries};message=`일괄 작업을 ${plans.length}개 반 편집본에 적용했습니다. 시간표 저장을 눌러 확정해 주세요.`;error=false;dialog.close();render();};
  dialog.showModal();
 }
 function holidayDialog(){
  const dialog=$('#editor');dialog.innerHTML=`<h3>대체휴일 · 이후 일정 순연</h3><p>선택일 이후 수업을 평일 기준 하루씩 미룹니다. 주말과 등록된 휴일은 건너뛰고, 같은 날 수업은 함께 이동합니다.</p><label>적용 반<select id="holidayClass">${option('all',selected,'전체 17개 반')}${classes.map(c=>option(String(c.id),selected,c.id+'반')).join('')}</select></label><label>휴일 날짜<input id="holidayDate" type="date" value="${date}"></label><label>휴일 이름<input id="holidayTitle" value="대체휴일" maxlength="100"></label><button id="holidayPreview">이동 미리보기</button><div id="holidayResult"></div><div id="holidayImpact"></div><div class="actions"><button id="holidayClose">닫기</button><button id="holidayApply" class="primary" disabled>편집본에 적용</button></div>`;
  let plans=[];const reset=()=>{plans=[];$('#holidayApply').disabled=true;$('#holidayResult').textContent='';$('#holidayImpact').textContent='';$('#holidayImpact').impactTicket=Symbol();};for(const id of ['holidayClass','holidayDate','holidayTitle'])$('#'+id).oninput=reset;
  $('#holidayPreview').onclick=()=>{reset();const cid=$('#holidayClass').value,day=$('#holidayDate').value,title=$('#holidayTitle').value,targets=cid==='all'?classes:classes.filter(c=>String(c.id)===cid);try{plans=targets.map(c=>({classId:String(c.id),...shiftForHoliday(data(c.id).entries,day,{title,id:'holiday-'+c.id+'-'+day})}));$('#holidayResult').innerHTML=plans.map(p=>`<details open><summary>${p.classId}반 · ${p.changes.length}개 수업 · 마지막 일정 ${p.lastDate}</summary>${p.lastDate>seed.end?'<p class="dirty">기존 교육 종료일 이후로 일정이 연장됩니다.</p>':''}</details>`).join('');const button=$('#holidayApply');void showImpact($('#holidayImpact'),plans,{note:'아래 적용은 화면의 편집본만 바꿉니다. 시간표 저장 후 공개해야 담임에게 반영됩니다.'}).then(shown=>{if(shown)button.disabled=false;});}catch(e){plans=[];$('#holidayResult').textContent=e.message;}};
  $('#holidayClose').onclick=()=>dialog.close();$('#holidayApply').onclick=()=>{if(!plans.length)return;undo.push(structuredClone(pending));if(undo.length>10)undo.shift();for(const p of plans)pending[p.classId]={...data(p.classId),entries:p.entries};message=`${plans.length}개 반 휴일·순연 미리보기를 적용했습니다. 시간표 저장을 눌러 확정해 주세요.`;error=false;dialog.close();render();};dialog.showModal();
 }
 function reviewReference(){
  const p=plan(),dialog=$('#editor');
  dialog.innerHTML=`<h3>공장·주요 교육과정 분류 반영</h3><p>분해조립 실습과 공장견학을 구분하고, 과정별 과목명을 운영 시트에 맞춥니다.</p><ul><li>강의 목록 ${p.counts.catalog}개 항목</li><li>저장된 편집본 ${p.counts.draft}개 수업</li><li>현재 공개본 ${p.counts.published}개 수업</li></ul><p>날짜·일차·시간·강사·전달사항은 유지됩니다. 별도로 수정한 강의명은 자동으로 덮어쓰지 않습니다. 새 HW Python 과목은 목록에만 추가되며 일정은 배정하지 않습니다.</p>${p.conflicts.length?`<details><summary>개별 수정으로 유지하는 항목 ${p.conflicts.length}건</summary>${p.conflicts.map(x=>`<p>${esc(x)}</p>`).join('')}</details>`:''}<p id="referenceError" role="alert"></p><div class="actions"><button id="referenceCancel">취소</button><button id="referenceSave" class="primary">분류 반영</button></div>`;
  $('#referenceCancel').onclick=()=>dialog.close();$('#referenceSave').onclick=async()=>{const b=$('#referenceSave');b.disabled=true;try{await store.applyCurriculum(p);await load();message=`시트 기준 분류 반영 완료 · 편집본 ${p.counts.draft}개, 공개본 ${p.counts.published}개 수업 · 수업 날짜 유지${p.conflicts.length?' · 개별 수정 '+p.conflicts.length+'건 유지':''}`;error=false;dialog.close();render();}catch(e){$('#referenceError').textContent=e.message;b.disabled=false;}};dialog.showModal();
 }
 function referenceSummary(){
  const groups=[];for(const f of reference.facilities){let g=groups.find(g=>g.factory===f.factory&&g.disassembly===f.disassembly);if(!g){g={...f,classes:[]};groups.push(g);}g.classes.push(f.classId);}
  return `<section class="card curriculum-reference"><h3>공장견학 · 분해조립 장소</h3><table><thead><tr><th>반</th><th>공장견학 · 견학·이론</th><th>분해조립 · 실습</th></tr></thead><tbody>${groups.map(g=>`<tr><th>${g.classes.join('·')}반</th><td>${esc(g.factory)}</td><td>${esc(g.disassembly)}</td></tr>`).join('')}</tbody></table><p class="muted">수업 날짜는 기존 일정표를 유지합니다. 만족도 조사날짜와 설문 실행 여부는 수업 일정·진행 상태로 사용하지 않습니다.</p><p class="muted">기준: ${reference.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a>`).join(' · ')}</p></section>`;
 }
 function pickClass(targetDate){
  const dialog=$('#editor');dialog.innerHTML=`<h3>어느 반에 일정을 추가할까요?</h3><form id="pickClass"><label>반<select name="classId" required>${classes.map(c=>option(String(c.id),'',`${c.id}반 · ${c.course}`)).join('')}</select></label><div class="actions"><button type="button" id="cancel">취소</button><button type="submit" class="primary">다음</button></div></form>`;
  $('#cancel').onclick=()=>dialog.close();$('#pickClass').onsubmit=ev=>{ev.preventDefault();const cid=new FormData(ev.target).get('classId');dialog.close();editEntry(cid,null,targetDate);};dialog.showModal();
 }
 function editEntry(cid,entry,targetDate=date){
  if(!cid)return pickClass(targetDate);
  const base=data(cid),expected=base.revision||0,defaults=catalog.lectures.find(l=>l.course===(meta(cid).course?.startsWith('제조')?'제조지능화':meta(cid).course))||catalog.lectures[0];
  const e=entry?{...entry}:{id:id(),date:targetDate,...defaults,lectureId:defaults.id,day:1,hours:8,start:'',end:'',instructorId:'',venue:meta(cid).venue||'',note:'',online:false,kind:'class'};
  if(!entry)e.id=id();const dialog=$('#editor');
  dialog.innerHTML=`<h3>${cid}반 · ${entry?'수업 수정':'일정 추가'}</h3><form id="entryForm"><div class="form-grid"><label>교육일자<input name="date" type="date" value="${e.date}" required></label><label>과정<select name="course">${catalog.courses.map(x=>option(x,e.course)).join('')}</select></label><label>모듈<select name="module"></select></label><label>강의<select name="lectureId"></select></label><label>강의 일차<input name="day" type="number" min="1" max="100" value="${e.day||1}" required></label><label>교육시간 (시간)<input name="hours" type="number" min="0" max="24" step="0.5" value="${e.hours||0}"></label><label>시작 시각<input name="start" type="time" value="${e.start||''}"></label><label>종료 시각<input name="end" type="time" value="${e.end||''}"></label><label>강사<select name="instructorId" aria-label="강사">${option('',e.instructorId,'미등록')}${Object.entries(instructors).map(([k,v])=>option(k,e.instructorId,v.name)).join('')}</select></label><label>장소<input name="venue" value="${esc(e.venue||'')}" maxlength="200"></label><label>일정 구분<select name="kind">${option('class',e.kind,'수업·행사')}${option('holiday',e.kind,'휴일·휴강')}</select></label><label>방식<select name="online">${option('false',String(e.online),'대면')}${option('true',String(e.online),'비대면')}</select></label><label class="full">전달사항<textarea name="note" maxlength="1000">${esc(e.note||'')}</textarea></label></div><div class="batch"><label><span><input name="sameLecture" type="checkbox"> 이 반의 같은 강의 전체 일차에 강사·장소 함께 적용</span></label><label style="margin-top:10px">이 일정을 다른 반에도 복사 (선택)<select name="copyTo"><option value="">복사 안 함</option>${classes.filter(c=>String(c.id)!==cid).map(c=>option(String(c.id),'',c.id+'반')).join('')}</select></label></div>${entry&&entry.kind!=='holiday'?`<div class="move-row"><span class="muted">순서 바꾸기 (저장 전 이동으로 보관)</span><button type="button" id="swapPrev" ${neighbour(base.entries,entry.id,-1)?'':'disabled'}>◀ 앞 수업과 바꾸기</button><button type="button" id="swapNext" ${neighbour(base.entries,entry.id,1)?'':'disabled'}>뒤 수업과 바꾸기 ▶</button></div>`:''}<div id="entryImpact"></div><p id="formError" role="alert" class="muted"></p><div class="actions"><button type="button" id="cancel">취소</button><button type="submit" class="primary">편집본 저장</button></div></form>`;
  const f=$('#entryForm'),el=n=>f.elements.namedItem(n);
  function lectures(wanted=e.lectureId){const list=catalog.lectures.filter(l=>l.course===el('course').value&&l.module===el('module').value);el('lectureId').innerHTML=list.map(l=>option(l.id,wanted,l.title)).join('')||'<option value="">강의 관리에서 먼저 등록</option>';}
  function modules(wanted=e.module){const list=[...new Set(catalog.lectures.filter(l=>l.course===el('course').value).map(l=>l.module))];el('module').innerHTML=list.map(m=>option(m,wanted)).join('');lectures();}
  modules();
  let previousVenue=catalog.lectures.find(l=>l.id===e.lectureId)?.venue||(!entry?e.venue:'')||'';
  function suggestVenue(){const value=catalog.lectures.find(l=>l.id===el('lectureId').value)?.venue||'';if(!el('venue').value||el('venue').value===previousVenue)el('venue').value=value;previousVenue=value;}
  el('course').onchange=()=>{modules();suggestVenue();};el('module').onchange=()=>{lectures();suggestVenue();};el('lectureId').onchange=suggestVenue;
  // Imported holidays retain their label, without inventing a lecture or a teaching day.
  if(e.kind==='holiday'){el('module').innerHTML+=option('휴일','휴일');el('module').value='휴일';el('lectureId').innerHTML=option('', '', e.title);}
  $('#cancel').onclick=()=>dialog.close();
  for(const [key,step] of [['swapPrev',-1],['swapNext',1]])if($('#'+key))$('#'+key).onclick=()=>{const other=neighbour(base.entries,entry.id,step);if(!other)return;try{const next=swapLesson(base.entries,entry.id,other.id);dialog.close();applyPending(cid,next,`${entry.title} ↔ ${other.title} 날짜를 맞바꿨습니다`);}catch(err){$('#formError').textContent=err.message;}};
  const copyId=id();
  function entryChanges(){
   const v=Object.fromEntries(new FormData(f)),l=catalog.lectures.find(l=>l.id===v.lectureId);if(!l&&v.kind!=='holiday')throw Error('강의를 먼저 선택해 주세요.');
   const next=validateEntry({...e,date:v.date,course:v.course,module:v.kind==='holiday'?'휴일':v.module,lectureId:v.lectureId,title:l?.title||e.title,day:v.kind==='holiday'?0:Number(v.day),hours:Number(v.hours),start:v.start,end:v.end,instructorId:v.instructorId,venue:v.venue,note:v.note,online:v.online==='true',kind:v.kind});
   let entries=base.entries.filter(x=>x.id!==next.id);entries.push(next);if(v.sameLecture)entries=entries.map(x=>x.lectureId===next.lectureId&&x.kind!=='holiday'?{...x,instructorId:next.instructorId,venue:next.venue}:x);
   const changes=[{classId:cid,entries:sortEntries(entries),seedVersion:base.seedVersion,revision:expected}];
   if(v.copyTo){const other=data(v.copyTo),copy={...next,id:copyId};changes.push({classId:v.copyTo,entries:sortEntries([...other.entries,copy]),seedVersion:other.seedVersion,revision:other.revision||0});}
   return{changes,next};
  }
  let editEpoch=0;
  function previewEntry(){const n=++editEpoch,button=f.querySelector('[type="submit"]'),target=$('#entryImpact');button.disabled=true;try{const {changes}=entryChanges();void showImpact(target,changes).then(shown=>{if(shown&&n===editEpoch)button.disabled=false;});}catch(err){target.impactTicket=Symbol();target.innerHTML='<p class="muted">날짜와 수업 정보를 입력하면 변경 영향을 확인할 수 있습니다.</p>';if(n===editEpoch)button.disabled=false;}}
  f.addEventListener('input',previewEntry);f.addEventListener('change',previewEntry);previewEntry();
  f.onsubmit=async event=>{event.preventDefault();const button=f.querySelector('[type="submit"]');button.disabled=true;try{
   const {changes,next}=entryChanges(),clash=conflicts(next,combined(),cid);if(clash.length&&!confirm(`같은 강사의 일정이 겹치거나 시각 확인이 필요합니다.\n${clash.map(x=>x.classId+'반 '+x.date+' '+x.title).join('\n')}\n그래도 저장할까요?`))return;
   drafts={...drafts,...await store.saveDrafts(changes)};for(const c of changes)delete pending[c.classId];undo=[];planCache=null;
   message='편집본을 저장했습니다. 확인 후 담임에게 공개해 주세요.';error=false;dialog.close();render();
  }catch(err){$('#formError').textContent=err.message;}finally{button.disabled=false;}};dialog.showModal();
 }

 function renderCatalog(body){
  body.innerHTML=`<div class="toolbar"><button id="addCourse">+ 과정</button><button id="addModule">+ 모듈</button><button id="addLecture" class="primary">+ 강의</button><span class="muted">과정 → 모듈 → 강의 → 일차. 목록 수정이 기존 반 일정을 바꾸지는 않습니다.</span></div>${referenceSummary()}<div class="chips">${catalog.courses.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><div class="cards">${catalog.courses.map(course=>`<section class="card"><h3>${esc(course)}</h3>${reference.courses[course]?`<p class="muted">시트 기준 주요 교육과정 ${reference.courses[course].length}개 · 공통·체험 과목 별도</p>`:''}${catalog.modules.map(m=>{const ls=catalog.lectures.filter(l=>l.course===course&&l.module===m);return ls.length?`<h4>${esc(m)}</h4>${ls.map(l=>`<button style="display:block;width:100%;margin:6px 0;text-align:left" data-lecture="${esc(l.id)}">${esc(l.title)} <small>· ${l.days?l.days+'일':'일차 미등록'}</small></button>`).join('')}`:'';}).join('')}</section>`).join('')}</div>`;
  for(const [key,field,label] of [['addCourse','courses','과정'],['addModule','modules','모듈']])$('#'+key).onclick=()=>{const name=prompt(`추가할 ${label} 이름`);if(!name?.trim())return;action(async()=>{if(name.length>80)throw Error('이름은 80자 이내로 입력해 주세요.');catalog=await store.saveCatalog({...catalog,[field]:[...new Set([...catalog[field],name.trim()])]},catalog.revision||0);message=label+'을 추가했습니다.';});};
  $('#addLecture').onclick=()=>editLecture();root.querySelectorAll('[data-lecture]').forEach(b=>b.onclick=()=>editLecture(catalog.lectures.find(l=>l.id===b.dataset.lecture)));
 }
 function editLecture(existing){const l=existing||{id:id(),course:catalog.courses[0],module:catalog.modules[0],title:'',days:1},dialog=$('#editor'),revision=catalog.revision||0;dialog.innerHTML=`<h3>강의 ${existing?'수정':'추가'}</h3><form id="lectureForm"><div class="form-grid"><label>과정<select name="course">${catalog.courses.map(x=>option(x,l.course)).join('')}</select></label><label>모듈<select name="module">${catalog.modules.map(x=>option(x,l.module)).join('')}</select></label><label class="full">강의명<input name="title" required maxlength="200" value="${esc(l.title)}"></label><label>총 일차<input name="days" required type="number" min="1" max="100" value="${l.days??''}"></label></div><p id="formError" role="alert"></p><div class="actions"><button id="cancel" type="button">취소</button><button type="submit" class="primary">저장</button></div></form>`;$('#cancel').onclick=()=>dialog.close();$('#lectureForm').onsubmit=async ev=>{ev.preventDefault();const b=ev.target.querySelector('[type="submit"]');b.disabled=true;try{const v=Object.fromEntries(new FormData(ev.target));if(!v.title.trim())throw Error('강의명을 입력해 주세요.');catalog=await store.saveCatalog({...catalog,lectures:[...catalog.lectures.filter(x=>x.id!==l.id),{...l,...v,title:v.title.trim(),days:Number(v.days)}]},revision);planCache=null;dialog.close();message='강의 목록을 저장했습니다. 기존 날짜별 배정은 유지됩니다.';render();}catch(e){$('#formError').textContent=e.message;}finally{b.disabled=false;}};dialog.showModal();}
 function instructorWeek(){
  const all=combined(),rows=Object.entries(all).flatMap(([cid,c])=>(c.entries||[]).filter(e=>e.instructorId&&e.kind!=='holiday').map(e=>({cid,...e}))),days=hideWeekend(weekDays(date),rows,showWeekend),inWeek=rows.filter(e=>days.includes(e.date));
  const people=Object.entries(instructors).filter(([k])=>inWeek.some(e=>e.instructorId===k)).sort((a,b)=>a[1].name.localeCompare(b[1].name,'ko'));
  return `<section class="card instructor-week"><div class="top"><h3>강사 주간 일정</h3><div class="date-nav"><button id="iwPrev" aria-label="이전 주">‹</button><label>기준 날짜<input id="iwDate" type="date" value="${date}"></label><button id="iwNext" aria-label="다음 주">›</button><button id="iwToday">이번 주</button></div></div>${people.length?`<div class="schedule-scroll"><div class="admin-grid" style="grid-template-columns:125px repeat(${days.length},minmax(150px,1fr));min-width:${125+days.length*150}px"><div class="grid-head">강사</div>${days.map(d=>`<div class="grid-head">${d.slice(5).replace('-','/')} (${weekday(d)})</div>`).join('')}${people.map(([k,v])=>`<div class="class-label"><b>${esc(v.name)}</b><div class="muted">${esc(v.organization||'')}</div></div>${days.map(d=>`<div class="day-cell">${sortEntries(inWeek.filter(e=>e.instructorId===k&&e.date===d)).map(e=>{const warn=warnings.get(e.cid+'|'+e.id);return `<div class="slot ${warn?'clash':''}" ${warn?`title="${esc(warn)}"`:''}><b>${esc(e.cid)}반</b> ${esc(e.title)}${e.day?' · '+e.day+'일차':''}<small>${e.start?esc(e.start+'–'+e.end):'시각 미등록'}${warn?' · ⚠ 겹침':''}</small></div>`;}).join('')}</div>`).join('')}`).join('')}</div></div>`:'<p class="muted">이 주에 강사가 배정된 수업이 없습니다. 시간표의 수업 수정이나 일괄 작업에서 강사를 배정해 주세요.</p>'}</section>`;
 }
 function renderInstructors(body){body.innerHTML=`<div class="toolbar"><button id="addInstructor" class="primary">+ 강사 등록</button><span class="muted">연락처·소속·관리 메모는 관리자에게만 표시합니다.</span></div>${instructorWeek()}<div class="cards">${Object.entries(instructors).map(([key,v])=>{const assigned=Object.entries(combined()).flatMap(([cid,c])=>c.entries.filter(e=>e.instructorId===key&&e.kind!=='holiday').map(e=>({cid,...e})));return `<section class="card"><h3>${esc(v.name)}</h3><p>${esc(v.organization||'소속 미등록')}<br>${esc(v.phone||'연락처 미등록')}</p><p class="muted">${esc(v.note||'')}</p><button data-instructor="${esc(key)}">정보 수정</button><details><summary>배정 일정 ${assigned.length}건</summary>${sortEntries(assigned).map(e=>`<p class="muted">${esc(e.date)} · ${esc(e.cid)}반 · ${esc(e.title)} ${e.day}일차</p>`).join('')}</details></section>`;}).join('')||'<div class="empty">등록된 강사가 없습니다. 이름과 연락처를 등록한 뒤 시간표에서 배정해 주세요.</div>'}</div>`;$('#addInstructor').onclick=()=>editInstructor();$('#iwDate').onchange=e=>{if(e.target.value&&e.target.value!==date){date=e.target.value;render();}};$('#iwToday').onclick=()=>{date=todayKST();render();};for(const [key,delta]of [['iwPrev',-7],['iwNext',7]])$('#'+key).onclick=()=>{const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+delta);date=d.toISOString().slice(0,10);render();};root.querySelectorAll('[data-instructor]').forEach(b=>b.onclick=()=>editInstructor(b.dataset.instructor));}
 function editInstructor(key=id()){const v=instructors[key]||{name:'',organization:'',phone:'',note:'',revision:0},dialog=$('#editor');dialog.innerHTML=`<h3>강사 정보</h3><form id="instructorForm"><div class="form-grid">${[['name','이름'],['organization','소속'],['phone','연락처'],['note','관리 메모']].map(([k,t])=>`<label>${t}<input name="${k}" maxlength="${k==='note'?500:100}" value="${esc(v[k])}" ${k==='name'?'required':''}></label>`).join('')}</div><p id="formError" role="alert"></p><div class="actions"><button id="cancel" type="button">취소</button><button type="submit" class="primary">저장</button></div></form>`;$('#cancel').onclick=()=>dialog.close();$('#instructorForm').onsubmit=async ev=>{ev.preventDefault();const b=ev.target.querySelector('[type="submit"]');b.disabled=true;try{const values=Object.fromEntries(new FormData(ev.target));if(!values.name.trim())throw Error('강사 이름을 입력해 주세요.');instructors[key]=await store.save('instructors',key,values,v.revision||0);message='강사 정보를 저장했습니다. 공개 일정의 강사명 변경은 해당 반을 다시 공개하면 반영됩니다.';dialog.close();render();}catch(e){$('#formError').textContent=e.message;}finally{b.disabled=false;}};dialog.showModal();}
 try{await load();render();}catch(e){content.innerHTML=`<div class="message error">시간표를 불러오지 못했습니다. ${esc(e.message)}</div>`;}
 return {canLeave:leave,dispose(){disposed=true;board.dispose();window.removeEventListener('beforeunload',beforeUnload);}};
}
const shortDate=d=>d&&d!=='없음'?d.slice(5,10).replace('-','/')+d.slice(10):d;
function changeLabel(c){
 if(c.kind==='추가')return '새 일정';
 const moved=c.from.slice(0,10)!==c.to.slice(0,10),rest=c.fields.filter(f=>!['날짜','시작','종료'].includes(f));
 return '변경됨 · '+[moved?`${shortDate(c.from)} → ${shortDate(c.to)}`:c.from!==c.to?`시간 ${shortDate(c.to)}`:'',rest.join('·')].filter(Boolean).join(' · ');
}
function printSchedule(entries,meta,changed){
 const w=window.open('','_blank');if(!w){alert('팝업이 차단되었습니다. 브라우저에서 이 사이트의 팝업을 허용해 주세요.');return;}
 const rows=sortEntries(entries).map(e=>`<tr class="${e.kind==='holiday'?'holiday':''}"><td>${esc(e.date.slice(5).replace('-','/'))} (${weekday(e.date)})</td><td>${esc(e.module)}</td><td><b>${esc(e.title)}</b>${e.day?' · '+e.day+'일차':''}${changed.has(e.id)?` <span class="tag">${esc(changed.get(e.id))}</span>`:''}</td><td>${esc(e.start?e.start+'–'+e.end:e.hours?e.hours+'시간':'')}</td><td>${esc(e.kind==='holiday'?'':e.instructorName||'')}</td><td>${esc([e.online?'비대면':'',e.venue,e.note].filter(Boolean).join(' · '))}</td></tr>`).join('');
 w.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>HINT ${esc(meta.id)}반 시간표</title><style>body{font-family:Pretendard,'Malgun Gothic',sans-serif;color:#142b48;margin:24px}h1{font-size:20px;margin:0 0 4px}p{color:#5b6f86;font-size:12px;margin:0 0 14px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #cfd9e6;padding:5px 7px;text-align:left;vertical-align:top}th{background:#edf3fa}thead{display:table-header-group}tr{break-inside:avoid}.holiday td{background:#f3f5f8;color:#6b7b8e}.tag{font-size:10px;background:#fff0c2;color:#774900;padding:1px 4px;border-radius:3px}@page{size:A4;margin:12mm}@media print{body{margin:0}}</style></head><body><h1>HINT ${esc(meta.id)}반 시간표</h1><p>${esc(meta.course||'')}${meta.venue?' · '+esc(meta.venue):''} · ${todayKST()} 기준 공개 일정 · 인쇄 창에서 'PDF로 저장'을 고르면 PDF 파일이 됩니다.</p><table><thead><tr><th>날짜</th><th>모듈</th><th>강의</th><th>시간</th><th>강사</th><th>장소·비고</th></tr></thead><tbody>${rows}</tbody></table><script>addEventListener('load',()=>setTimeout(()=>print(),200));<\/script></body></html>`);
 w.document.close();
}
function downloadIcs(entries,meta){
 const url=URL.createObjectURL(new Blob([toIcs(entries,{classId:meta.id,course:meta.course})],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');
 a.href=url;a.download=`hint-class${meta.id}-timetable.ics`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function renderTeacher(host,entries,meta,{compact=false,changes=[]}={}){
 const root=shell(host),content=root.querySelector('#content');let date=todayKST(),mode='week',showWeekend=false;
 const changed=new Map(changes.filter(c=>c.kind!=='삭제').map(c=>[c.id,changeLabel(c)])),seenKey=`hint-timetable-seen-${meta.id}`,signature=changes.length?changes[0].at+'|'+changes.length:'';
 const readSeen=()=>{try{return localStorage.getItem(seenKey)||'';}catch{return '';}};
 const card=(e,ends)=>lesson(e,{},false,meta.id,ends.has(e.id),{changed:changed.get(e.id)});
 function changePanel(){
  if(!changes.length)return '';const unseen=readSeen()!==signature;
  return `<details class="change-panel" ${unseen?'open':''}><summary>최근 2주 시간표 변경 ${changes.length}건${unseen?' <span class="new">NEW</span>':''}</summary><ul>${changes.map(c=>`<li><b>${esc(c.title)}${c.day?' · '+c.day+'일차':''}</b> <span>${esc(c.kind==='삭제'?'일정 삭제 · '+shortDate(c.from):c.kind==='추가'?'새 일정 · '+shortDate(c.to):changeLabel(c).replace('변경됨 · ',''))}</span><small>${esc(c.at)} 공개</small></li>`).join('')}</ul>${unseen?'<button id="seenChanges">확인했어요</button>':''}</details>`;
 }
 function render(){const ends=new Set(lectureEndDays(entries).map(e=>e.id));const current=visibleToday(entries),all=mode==='month'?monthDays(date):weekDays(date),days=hideWeekend(all,entries,showWeekend),cols=mode==='month'?days.length/6:days.length;
  content.innerHTML=`<section class="today-panel"><div class="eyebrow" style="color:#bbd6f9">MY CLASS · ${esc(meta.id)}반</div><h3>오늘의 수업 <small>${todayKST().slice(5).replace('-','/')} (${weekday(todayKST())})</small></h3>${current.today.length?current.today.map(e=>card(e,ends)).join(''):`<p>${entries.length?'오늘은 예정된 수업이 없습니다.':'아직 공개된 시간표가 없습니다.'}</p>${current.next?`<div class="muted">다음 수업 · ${esc(current.next.date)} · ${esc(current.next.title)}</div>`:''}`}${changePanel()}</section><section class="teacher-calendar"><div class="top"><h2>우리 반 전체 일정</h2><span class="muted">${esc(meta.course||'')} · ${esc(meta.venue||'')}${progressText(classProgress(entries))?' · '+esc(progressText(classProgress(entries))):''}</span></div><div class="toolbar switch"><button id="week" class="${mode==='week'?'active':''}">주간</button><button id="month" class="${mode==='month'?'active':''}">월간</button><button id="previous" aria-label="이전 기간">‹</button><label>기준 날짜<input id="date" type="date" value="${date}"></label><button id="next" aria-label="다음 기간">›</button><button id="today">오늘</button><label class="inline-check"><input id="weekendToggle" type="checkbox" ${showWeekend?'checked':''}> 주말 표시</label><span class="toolbar-spacer"></span><button id="printSchedule" ${entries.length?'':'disabled'}>인쇄·PDF</button><button id="icsSchedule" ${entries.length?'':'disabled'} title="구글·네이버·아웃룩 캘린더에서 가져오기로 추가할 수 있습니다">캘린더 파일(.ics)</button></div><div class="legend">${[...new Set(entries.map(e=>e.module))].map(m=>`<span style="${paint(m)}">${esc(m)}</span>`).join('')}</div><div class="schedule-scroll"><div class="month-grid" style="grid-template-columns:repeat(${cols},minmax(125px,1fr));min-width:${cols*125}px">${days.slice(0,cols).map(d=>`<div class="grid-head">${weekday(d)}</div>`).join('')}${days.map(d=>`<div class="day-cell ${d===todayKST()?'today':''} ${mode==='month'&&d.slice(0,7)!==date.slice(0,7)?'outside':''}"><div class="day-num">${d.slice(5).replace('-','/')}</div>${entries.filter(e=>e.date===d).map(e=>card(e,ends)).join('')}</div>`).join('')}</div></div><div class="mobile-list">${all.filter(d=>entries.some(e=>e.date===d)).map(d=>`<section class="card"><h3>${d.slice(5).replace('-','/')} (${weekday(d)})</h3>${entries.filter(e=>e.date===d).map(e=>card(e,ends)).join('')}</section>`).join('')||'<div class="empty">선택한 기간의 수업이 없습니다.</div>'}</div></section>`;
  const seen=root.querySelector('#seenChanges');if(seen)seen.onclick=()=>{try{localStorage.setItem(seenKey,signature);}catch{}render();};
  if(compact){root.querySelector('.teacher-calendar')?.remove();return;}
  for(const m of ['week','month'])root.querySelector('#'+m).onclick=()=>{mode=m;render();};root.querySelector('#date').onchange=e=>{if(e.target.value&&e.target.value!==date){date=e.target.value;render();}};root.querySelector('#today').onclick=()=>{date=todayKST();render();};for(const [key,delta]of [['previous',-1],['next',1]])root.querySelector('#'+key).onclick=()=>{const d=new Date(date+'T12:00:00Z');if(mode==='month'){d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+delta);}else d.setUTCDate(d.getUTCDate()+7*delta);date=d.toISOString().slice(0,10);render();};
  root.querySelector('#weekendToggle').onchange=e=>{showWeekend=e.target.checked;render();};root.querySelector('#printSchedule').onclick=()=>printSchedule(entries,meta,changed);root.querySelector('#icsSchedule').onclick=()=>downloadIcs(entries,meta);
 }render();
}
export async function mountTeacherTimetable(host,{db,user,classInfo,compact=false,includeSurveys=false}){await loadSurveyLinks();const root=shell(host);root.querySelector('#content').innerHTML='<div class="empty">우리 반 시간표를 불러오는 중…</div>';try{const [data,materials]=await Promise.all([createTimetableStore(db,user).read('published',classInfo.id),readMaterials(db,classInfo.id,{user})]);if(host.isConnected){const entries=(data?.entries||[]).map(e=>({...e,materials:materials.filter(m=>m.lectureKey===(e.lectureId||e.title))}));renderTeacher(host,entries,classInfo,{compact,changes:data?.recentChanges||[]});}}catch(e){root.querySelector('#content').innerHTML=`<div class="message error">시간표 조회에 실패했습니다. ${esc(e.message)}</div>`;}}
