import {readMaterials,materialUrl} from './lecture-materials.mjs';
import {loadSurveyLinks,surveyLink} from './survey-links.mjs';
import {shiftForHoliday} from './timetable-holiday.mjs';
import {createTimetableBoard,moveLesson} from './timetable-board.mjs';
import {todayKST,weekDays,monthDays,sortEntries,validateEntry,conflicts,publishEntries,visibleToday,lectureEndDays,lectureEndsOn} from './timetable-core.mjs';
import {createTimetableStore} from './timetable-store.mjs';
import {curriculumPlan,correctedSeed} from './timetable-reference.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const palette={'동기부여':['#8864bb','#f4effb'],'디지털스킬':['#326ac0','#edf3fc'],'소프트스킬':['#4291a4','#edf7f9'],'직무특화':['#28685e','#ecf6f1'],'공장견학':['#b67726','#fff5e7'],'문화체험':['#bc5b80','#fceff4'],'진로탐색':['#5d67aa','#f0f0fc'],'현직자특강':['#be713a','#fff2e9'],'분해조립':['#548752','#f0f7ec'],'실차체험':['#548752','#f0f7ec'],'공통행사':['#a26148','#faf0ec'],'휴일':['#82909f','#f1f3f6']};
const paint=m=>{const c=palette[m]||['#65748b','#f0f4f8'];return `--module:${c[0]};--tint:${c[1]}`;};
const option=(value,selected,label=value)=>`<option value="${esc(value)}" ${value===selected?'selected':''}>${esc(label)}</option>`;
const weekday=d=>new Intl.DateTimeFormat('ko-KR',{weekday:'short',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
const id=()=>crypto.randomUUID();
function lesson(e,instructors={},click=false,cid='',ending=false){
 const name=e.instructorName||instructors[e.instructorId]?.name||'',time=e.start?`${e.start}–${e.end}`:e.hours?`${e.hours}시간 · 시각 미등록`:'';
 return `<div class="lesson-container"><${click?'button':'article'} class="lesson" style="${paint(e.module)}" ${click?`draggable="${e.kind!=='holiday'}" data-edit="${esc(e.id)}" data-cid="${esc(cid)}" aria-label="${esc(cid+'반 '+e.date+' '+e.title+' 수정')}"`:''}><small>${esc(e.module)}${e.online?' · 비대면':''}</small><strong>${esc(e.title)}${e.day?' · '+e.day+'일차':''}</strong><small>${esc(time)}</small>${e.kind==='holiday'?'':`<small>${esc(name||'강사 미등록')}${e.venue?' · '+esc(e.venue):''}</small>`}${e.note?`<small>${esc(e.note)}</small>`:''}</${click?'button':'article'}>${(e.materials||[]).map(m=>`<a class="lecture-end" target="_blank" rel="noopener" href="${esc(materialUrl(m.url))}">자료 · ${esc(m.title)} ↗</a>`).join('')}${ending?`<a class="lecture-end survey-lesson-link" href="${esc(surveyLink(cid,e))}" target="_blank" rel="noopener">모듈 종료일, 만족도조사 필요 ↗</a>`:''}</div>`;
}
function shell(host){const root=host.shadowRoot||host.attachShadow({mode:'open'});root.innerHTML='<link rel="stylesheet" href="/timetable.css?v=20260914-5"><div id="content"></div><dialog id="editor"></dialog>';return root;}
export async function mountTimetableAdmin(host,{db,user,classes}){
 const root=shell(host),store=createTimetableStore(db,user),$=s=>root.querySelector(s),content=$('#content');
 let seed,reference,catalog,drafts={},published={},instructors={},selected='all',date=todayKST(),mode='schedule',busy=false,message='',error=false,view='week',pending={},undo=[],disposed=false,planCache=null;
 const meta=cid=>classes.find(c=>String(c.id)===String(cid))||{id:cid};
 content.innerHTML='<div class="empty">시간표와 강사 정보를 불러오는 중…</div>';
 async function load(){planCache=null;await loadSurveyLinks();const r=await fetch('/timetable-seed.json');if(!r.ok)throw Error('기준 엑셀 일정을 읽지 못했습니다.');seed=await r.json();const rr=await fetch('/timetable-reference.json');if(!rr.ok)throw Error('교육과정 기준을 읽지 못했습니다.');reference=await rr.json();seed=correctedSeed(seed,reference);[catalog,drafts,published,instructors]=await Promise.all([store.catalog(seed),store.all('draft'),store.all('published'),store.all('instructors')]);}
 const plan=()=>planCache||(planCache=curriculumPlan(catalog,drafts,published,reference));
 const data=cid=>pending[cid]||drafts[cid]||seed.classes[cid]||{entries:[],revision:0};
 const combined=()=>Object.fromEntries(classes.map(c=>[c.id,data(c.id)]));
 const dirty=()=>Object.keys(pending);
 const board=createTimetableBoard({root,classes,data,lesson,instructors:()=>instructors,status:cid=>pending[cid]?'<span class="dirty">저장 전 이동</span>':!drafts[cid]?'<span class="dirty">엑셀 미저장</span>':published[cid]?.sourceRevision===drafts[cid]?.revision?'✓ 공개됨':'<span class="dirty">공개 전 변경</span>',onError:text=>{message=text;error=true;render();},onMove(cid,id,date,swapId){if(busy)return;const base=data(cid),entries=moveLesson(base.entries,id,date,swapId);if(entries===base.entries)return;undo.push(structuredClone(pending));if(undo.length>10)undo.shift();pending={...pending,[cid]:{...base,entries}};message=`${cid}반 · ${swapId?'수업을 끼워 넣고 사이 일정을 순서대로 옮겼습니다':'수업 날짜를 옮겼습니다'}. 시간표 저장을 눌러 확정해 주세요.`;error=false;render();}});
 const leave=()=>!busy&&(!dirty().length||confirm('저장하지 않은 시간표 이동이 있습니다. 저장하지 않고 나갈까요?'));
 const beforeUnload=e=>{if(dirty().length){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',beforeUnload);
 async function saveBoard(){if(!dirty().length)return;await action(async()=>{const changes=dirty().map(classId=>({classId,entries:data(classId).entries,revision:drafts[classId]?.revision||0}));const warnings=changes.flatMap(c=>c.entries.flatMap(e=>conflicts(e,combined(),c.classId)));if(warnings.length&&!confirm(`강사 일정 중복 또는 시각 확인이 필요한 항목이 ${warnings.length}건 있습니다. 그래도 시간표를 저장할까요?`)){message='이동한 시간표를 유지했습니다. 강사 일정을 확인해 주세요.';return;}const saved=await store.saveDrafts(changes);drafts={...drafts,...saved};pending={};undo=[];planCache=null;message='시간표 저장 완료 · 확인 후 담임에게 공개해 주세요.';});}
 root.addEventListener('click',e=>{if(busy)return;const edit=e.target.closest?.('[data-edit]'),add=e.target.closest?.('[data-add]');if(edit)editEntry(edit.dataset.cid,data(edit.dataset.cid).entries.find(x=>x.id===edit.dataset.edit));else if(add)editEntry(add.dataset.cid,null,add.dataset.add);});
 async function action(fn){if(busy||disposed)return;busy=true;message='처리 중…';error=false;render();try{await fn();}catch(e){message=e.message;error=true;}finally{busy=false;planCache=null;if(host.isConnected&&!disposed)render();}}
 function render(){
  if(disposed||!host.isConnected)return;const shown=selected==='all'?classes:classes.filter(c=>String(c.id)===selected),days=weekDays(date);
  content.innerHTML=`<div class="top"><div><div class="eyebrow">HINT / TIMETABLE BETA</div><h2>시간표 관리</h2><div class="muted">수업 날짜는 일정표 기준, 공장·교육과정은 운영 시트 기준입니다. 강사 연락처는 관리자만 확인합니다.</div></div><div class="actions"><button id="reload">↻ 새로고침</button><button id="import">엑셀 기준 17개 반 가져오기</button>${plan().changes.length?'<button id="referenceApply" class="primary">시트 기준 분류 반영</button>':''}</div></div><div class="toolbar switch">${[['schedule','반별 시간표'],['catalog','과정·강의 관리'],['instructors','강사 관리'],['preview','담임 화면 미리보기']].map(([v,t])=>`<button data-mode="${v}" class="${mode===v?'active':''}">${t}</button>`).join('')}</div>${message?`<div role="status" class="message ${error?'error':''}">${esc(message)}</div>`:''}<div id="body"></div>`;
  const body=$('#body');
  if(mode==='schedule'){
   body.innerHTML=`<div class="toolbar board-toolbar"><label>반<select id="classFilter">${option('all',selected,'전체 17개 반')}${classes.map(c=>option(String(c.id),selected,`${c.id}반 · ${c.course}`)).join('')}</select></label><div class="switch view-switch">${[['week','주간'],['month','월간'],['all','전체 일정']].map(([v,t])=>`<button data-period="${v}" class="${view===v?'active':''}">${t}</button>`).join('')}</div><button id="previous" aria-label="이전 기간" ${view==='all'?'disabled':''}>‹</button><label>기준 날짜<input id="date" type="date" value="${date}"></label><button id="next" aria-label="다음 기간" ${view==='all'?'disabled':''}>›</button><button id="today">오늘</button><button id="new">+ 일정 추가</button><button id="holidayShift">대체휴일 · 일정 순연</button><button id="undoMove" ${undo.length?'':'disabled'}>이동 되돌리기</button><button class="primary" id="saveTimetable" ${dirty().length?'':'disabled'}>시간표 저장${dirty().length?' ('+dirty().length+'개 반)':''}</button><button id="publish" ${dirty().length?'disabled':''}>${selected==='all'?'17개 반':'선택 반'} 담임에게 공개</button></div><p class="muted move-guide">같은 반의 빈 날짜로 끌면 이동 · 다른 수업 위에 놓으면 끼워넣기 · 사이 수업은 순서대로 이동 · 이동 후 시간표 저장 · 수업을 클릭하면 세부 수정</p>${shown.flatMap(c=>lectureEndsOn(data(c.id).entries,date).map(e=>`<div class="lecture-end notice">${esc(c.id)}반 · ${esc(e.title)} — <a href="${esc(surveyLink(c.id,e))}" target="_blank" rel="noopener">모듈 종료일, 만족도조사 필요 ↗</a></div>`)).join('')}<div class="legend">${catalog.modules.map(m=>`<span style="${paint(m)}">${esc(m)}</span>`).join('')}</div>${board.html({shown,view,date})}`;
   root.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{view=b.dataset.period;render();});$('#holidayShift').onclick=holidayDialog;$('#saveTimetable').onclick=saveBoard;$('#undoMove').onclick=()=>{if(undo.length){pending=undo.pop();message='이전 이동 상태로 되돌렸습니다.';error=false;render();}};
   $('#classFilter').onchange=e=>{selected=e.target.value;render();};$('#date').onchange=e=>{if(e.target.value){date=e.target.value;render();}};$('#today').onclick=()=>{date=todayKST();render();};
   for(const [key,delta] of [['previous',-1],['next',1]])$('#'+key).onclick=()=>{const d=new Date(date+'T12:00:00Z');if(view==='month'){d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+delta);}else d.setUTCDate(d.getUTCDate()+7*delta);date=d.toISOString().slice(0,10);render();};
   $('#new').onclick=()=>editEntry(selected==='all'?'1':selected,null,date);
   $('#publish').onclick=()=>{const targets=shown.filter(c=>drafts[c.id]);if(!targets.length){message='먼저 엑셀 기준 일정을 가져오거나 편집본을 저장해 주세요.';render();return;}if(!confirm(`${targets.length}개 반의 저장된 편집본을 담임에게 공개할까요?`))return;action(async()=>{let count=0;for(const c of targets){published[c.id]=await store.publish(String(c.id),drafts[c.id],published[c.id]?.revision||0,publishEntries(drafts[c.id].entries,instructors));count++;message=`${count}/${targets.length}개 반 공개 완료`;}});};
  }else if(mode==='catalog')renderCatalog(body);
  else if(mode==='instructors')renderInstructors(body);
  else {const cid=selected==='all'?'1':selected;body.innerHTML=`<div class="toolbar"><label>미리볼 반<select id="previewClass">${classes.map(c=>option(String(c.id),cid,`${c.id}반 · ${c.course}`)).join('')}</select></label><span class="muted">담임에게 공개한 일정만 표시합니다.</span></div><div id="preview"></div>`;$('#previewClass').onchange=e=>{selected=e.target.value;render();};renderTeacher($('#preview'),published[cid]?.entries||[],meta(cid));}
  root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render();});
  if($('#referenceApply'))$('#referenceApply').onclick=reviewReference;
  $('#reload').onclick=()=>{if(dirty().length&&!confirm('저장 전 이동을 버리고 최신 시간표를 다시 읽을까요?'))return;return action(async()=>{await load();pending={};undo=[];message='최신 시간표를 읽었습니다.';});};
  $('#import').onclick=()=>{const targets=classes.filter(c=>!drafts[c.id]);if(!targets.length){message='17개 반의 편집본이 이미 있습니다. 기존 일정은 유지됩니다.';render();return;}if(!confirm(`편집본이 없는 ${targets.length}개 반에 엑셀 일정을 가져올까요? 기존 편집본과 원본 엑셀은 유지됩니다.`))return;action(async()=>{let n=0;for(const c of targets){drafts[c.id]=await store.save('draft',c.id,{classId:String(c.id),entries:seed.classes[c.id].entries},0);message=`${++n}/${targets.length}개 반 가져오기 완료 · 확인 후 담임에게 공개해 주세요.`;}});};
  if(busy)root.querySelectorAll('button,input,select').forEach(b=>b.disabled=true);
 }
 function holidayDialog(){
  const dialog=$('#editor');dialog.innerHTML=`<h3>대체휴일 · 이후 일정 순연</h3><p>선택일 이후 수업을 평일 기준 하루씩 미룹니다. 주말과 등록된 휴일은 건너뛰고, 같은 날 수업은 함께 이동합니다.</p><label>적용 반<select id="holidayClass">${option('all',selected,'전체 17개 반')}${classes.map(c=>option(String(c.id),selected,c.id+'반')).join('')}</select></label><label>휴일 날짜<input id="holidayDate" type="date" value="${date}"></label><label>휴일 이름<input id="holidayTitle" value="대체휴일" maxlength="100"></label><button id="holidayPreview">이동 미리보기</button><div id="holidayResult"></div><div class="actions"><button id="holidayClose">닫기</button><button id="holidayApply" class="primary" disabled>편집본에 적용</button></div>`;
  let plans=[];const reset=()=>{plans=[];$('#holidayApply').disabled=true;$('#holidayResult').textContent='';};for(const id of ['holidayClass','holidayDate','holidayTitle'])$('#'+id).oninput=reset;
  $('#holidayPreview').onclick=()=>{reset();const cid=$('#holidayClass').value,day=$('#holidayDate').value,title=$('#holidayTitle').value,targets=cid==='all'?classes:classes.filter(c=>String(c.id)===cid);try{plans=targets.map(c=>({classId:String(c.id),...shiftForHoliday(data(c.id).entries,day,{title,id:'holiday-'+c.id+'-'+day})}));$('#holidayResult').innerHTML=plans.map(p=>`<details open><summary>${p.classId}반 · ${p.changes.length}개 수업 · 마지막 일정 ${p.lastDate}</summary>${p.lastDate>seed.end?'<p class="dirty">기존 교육 종료일 이후로 일정이 연장됩니다.</p>':''}<div style="max-height:220px;overflow:auto"><table><thead><tr><th>수업</th><th>기존</th><th>변경</th></tr></thead><tbody>${p.changes.map(e=>`<tr><td>${esc(e.title)}</td><td>${e.from}</td><td>${e.to}</td></tr>`).join('')}</tbody></table></div></details>`).join('');$('#holidayApply').disabled=false;}catch(e){plans=[];$('#holidayResult').textContent=e.message;}};
  $('#holidayClose').onclick=()=>dialog.close();$('#holidayApply').onclick=()=>{if(!plans.length)return;undo.push(structuredClone(pending));if(undo.length>10)undo.shift();for(const p of plans)pending[p.classId]={...data(p.classId),entries:p.entries};message=`${plans.length}개 반 휴일·순연 미리보기를 적용했습니다. 시간표 저장을 눌러 확정해 주세요.`;error=false;dialog.close();render();};dialog.showModal();
 }
 function reviewReference(){
  const p=plan(),dialog=$('#editor');
  dialog.innerHTML=`<h3>공장·주요 교육과정 분류 반영</h3><p>분해조립 실습과 공장견학을 구분하고, 과정별 과목명을 운영 시트에 맞춥니다.</p><ul><li>강의 목록 ${p.counts.catalog}개 항목</li><li>저장된 편집본 ${p.counts.draft}개 수업</li><li>현재 공개본 ${p.counts.published}개 수업</li></ul><p>날짜·일차·시간·강사·전달사항은 유지됩니다. 별도로 수정한 강의명은 자동으로 덮어쓰지 않습니다. 새 HW Python 과목은 목록에만 추가되며 일정은 배정하지 않습니다.</p>${p.conflicts.length?`<details><summary>개별 수정으로 유지하는 항목 ${p.conflicts.length}건</summary>${p.conflicts.map(x=>`<p>${esc(x)}</p>`).join('')}</details>`:''}<p id="referenceError" role="alert"></p><div class="actions"><button id="referenceCancel">취소</button><button id="referenceSave" class="primary">분류 반영</button></div>`;
  $('#referenceCancel').onclick=()=>dialog.close();$('#referenceSave').onclick=async()=>{const b=$('#referenceSave');b.disabled=true;try{await store.applyCurriculum(p);await load();message=`시트 기준 분류 반영 완료 · 편집본 ${p.counts.draft}개, 공개본 ${p.counts.published}개 수업 · 수업 날짜 유지${p.conflicts.length?' · 개별 수정 '+p.conflicts.length+'건 유지':''}`;error=false;dialog.close();render();}catch(e){$('#referenceError').textContent=e.message;b.disabled=false;}};dialog.showModal();
 }
 function referenceSummary(){
  const groups=[];for(const f of reference.facilities){let g=groups.find(g=>g.factory===f.factory&&g.disassembly===f.disassembly);if(!g){g={...f,classes:[]};groups.push(g);}g.classes.push(f.classId);}
  return `<section class="card curriculum-reference"><h3>공장견학 · 분해조립 장소</h3><table><thead><tr><th>반</th><th>공장견학 · 견학·이론</th><th>분해조립 · 실습</th></tr></thead><tbody>${groups.map(g=>`<tr><th>${g.classes.join('·')}반</th><td>${esc(g.factory)}</td><td>${esc(g.disassembly)}</td></tr>`).join('')}</tbody></table><p class="muted">수업 날짜는 기존 일정표를 유지합니다. 만족도 조사날짜와 설문 실행 여부는 수업 일정·진행 상태로 사용하지 않습니다.</p><p class="muted">기준: ${reference.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a>`).join(' · ')}</p></section>`;
 }
 function editEntry(cid,entry,targetDate=date){
  const base=data(cid),expected=base.revision||0,defaults=catalog.lectures.find(l=>l.course===(meta(cid).course?.startsWith('제조')?'제조지능화':meta(cid).course))||catalog.lectures[0];
  const e=entry?{...entry}:{id:id(),date:targetDate,...defaults,lectureId:defaults.id,day:1,hours:8,start:'',end:'',instructorId:'',venue:meta(cid).venue||'',note:'',online:false,kind:'class'};
  if(!entry)e.id=id();const dialog=$('#editor');
  dialog.innerHTML=`<h3>${cid}반 · ${entry?'수업 수정':'일정 추가'}</h3><form id="entryForm"><div class="form-grid"><label>교육일자<input name="date" type="date" value="${e.date}" required></label><label>과정<select name="course">${catalog.courses.map(x=>option(x,e.course)).join('')}</select></label><label>모듈<select name="module"></select></label><label>강의<select name="lectureId"></select></label><label>강의 일차<input name="day" type="number" min="1" max="100" value="${e.day||1}" required></label><label>교육시간 (시간)<input name="hours" type="number" min="0" max="24" step="0.5" value="${e.hours||0}"></label><label>시작 시각<input name="start" type="time" value="${e.start||''}"></label><label>종료 시각<input name="end" type="time" value="${e.end||''}"></label><label>강사<select name="instructorId" aria-label="강사">${option('',e.instructorId,'미등록')}${Object.entries(instructors).map(([k,v])=>option(k,e.instructorId,v.name)).join('')}</select></label><label>장소<input name="venue" value="${esc(e.venue||'')}" maxlength="200"></label><label>일정 구분<select name="kind">${option('class',e.kind,'수업·행사')}${option('holiday',e.kind,'휴일·휴강')}</select></label><label>방식<select name="online">${option('false',String(e.online),'대면')}${option('true',String(e.online),'비대면')}</select></label><label class="full">전달사항<textarea name="note" maxlength="1000">${esc(e.note||'')}</textarea></label></div><div class="batch"><label><span><input name="sameLecture" type="checkbox"> 이 반의 같은 강의 전체 일차에 강사·장소 함께 적용</span></label><label style="margin-top:10px">이 일정을 다른 반에도 복사 (선택)<select name="copyTo"><option value="">복사 안 함</option>${classes.filter(c=>String(c.id)!==cid).map(c=>option(String(c.id),'',c.id+'반')).join('')}</select></label></div><p id="formError" role="alert" class="muted"></p><div class="actions"><button type="button" id="cancel">취소</button><button type="submit" class="primary">편집본 저장</button></div></form>`;
  const f=$('#entryForm'),el=n=>f.elements.namedItem(n);
  function lectures(wanted=e.lectureId){const list=catalog.lectures.filter(l=>l.course===el('course').value&&l.module===el('module').value);el('lectureId').innerHTML=list.map(l=>option(l.id,wanted,l.title)).join('')||'<option value="">강의 관리에서 먼저 등록</option>';}
  function modules(wanted=e.module){const list=[...new Set(catalog.lectures.filter(l=>l.course===el('course').value).map(l=>l.module))];el('module').innerHTML=list.map(m=>option(m,wanted)).join('');lectures();}
  modules();
  let previousVenue=catalog.lectures.find(l=>l.id===e.lectureId)?.venue||(!entry?e.venue:'')||'';
  function suggestVenue(){const value=catalog.lectures.find(l=>l.id===el('lectureId').value)?.venue||'';if(!el('venue').value||el('venue').value===previousVenue)el('venue').value=value;previousVenue=value;}
  el('course').onchange=()=>{modules();suggestVenue();};el('module').onchange=()=>{lectures();suggestVenue();};el('lectureId').onchange=suggestVenue;
  // Imported holidays retain their label, without inventing a lecture or a teaching day.
  if(e.kind==='holiday'){el('module').innerHTML+=option('휴일','휴일');el('module').value='휴일';el('lectureId').innerHTML=option('', '', e.title);}
  $('#cancel').onclick=()=>dialog.close();
  f.onsubmit=async event=>{event.preventDefault();const button=f.querySelector('[type="submit"]');button.disabled=true;try{
   const v=Object.fromEntries(new FormData(f)),l=catalog.lectures.find(l=>l.id===v.lectureId);if(!l&&v.kind!=='holiday')throw Error('강의를 먼저 선택해 주세요.');
   const next=validateEntry({...e,date:v.date,course:v.course,module:v.kind==='holiday'?'휴일':v.module,lectureId:v.lectureId,title:l?.title||e.title,day:v.kind==='holiday'?0:Number(v.day),hours:Number(v.hours),start:v.start,end:v.end,instructorId:v.instructorId,venue:v.venue,note:v.note,online:v.online==='true',kind:v.kind});
   const clash=conflicts(next,combined(),cid);if(clash.length&&!confirm(`같은 강사의 일정이 겹치거나 시각 확인이 필요합니다.\n${clash.map(x=>x.classId+'반 '+x.date+' '+x.title).join('\n')}\n그래도 저장할까요?`))return;
   let entries=base.entries.filter(x=>x.id!==next.id);entries.push(next);if(v.sameLecture)entries=entries.map(x=>x.lectureId===next.lectureId&&x.kind!=='holiday'?{...x,instructorId:next.instructorId,venue:next.venue}:x);
   const changes=[{classId:cid,entries:sortEntries(entries),revision:expected}];
   if(v.copyTo){const other=data(v.copyTo),copy={...next,id:id()};changes.push({classId:v.copyTo,entries:sortEntries([...other.entries,copy]),revision:other.revision||0});}
   drafts={...drafts,...await store.saveDrafts(changes)};for(const c of changes)delete pending[c.classId];undo=[];planCache=null;
   message='편집본을 저장했습니다. 확인 후 담임에게 공개해 주세요.';error=false;dialog.close();render();
  }catch(err){$('#formError').textContent=err.message;}finally{button.disabled=false;}};dialog.showModal();
 }
 function renderCatalog(body){
  body.innerHTML=`<div class="toolbar"><button id="addCourse">+ 과정</button><button id="addModule">+ 모듈</button><button id="addLecture" class="primary">+ 강의</button><span class="muted">과정 → 모듈 → 강의 → 일차. 목록 수정이 기존 반 일정을 바꾸지는 않습니다.</span></div>${referenceSummary()}<div class="chips">${catalog.courses.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><div class="cards">${catalog.courses.map(course=>`<section class="card"><h3>${esc(course)}</h3>${reference.courses[course]?`<p class="muted">시트 기준 주요 교육과정 ${reference.courses[course].length}개 · 공통·체험 과목 별도</p>`:''}${catalog.modules.map(m=>{const ls=catalog.lectures.filter(l=>l.course===course&&l.module===m);return ls.length?`<h4>${esc(m)}</h4>${ls.map(l=>`<button style="display:block;width:100%;margin:6px 0;text-align:left" data-lecture="${esc(l.id)}">${esc(l.title)} <small>· ${l.days?l.days+'일':'일차 미등록'}</small></button>`).join('')}`:'';}).join('')}</section>`).join('')}</div>`;
  for(const [key,field,label] of [['addCourse','courses','과정'],['addModule','modules','모듈']])$('#'+key).onclick=()=>{const name=prompt(`추가할 ${label} 이름`);if(!name?.trim())return;action(async()=>{if(name.length>80)throw Error('이름은 80자 이내로 입력해 주세요.');catalog=await store.saveCatalog({...catalog,[field]:[...new Set([...catalog[field],name.trim()])]},catalog.revision||0);message=label+'을 추가했습니다.';});};
  $('#addLecture').onclick=()=>editLecture();root.querySelectorAll('[data-lecture]').forEach(b=>b.onclick=()=>editLecture(catalog.lectures.find(l=>l.id===b.dataset.lecture)));
 }
 function editLecture(existing){const l=existing||{id:id(),course:catalog.courses[0],module:catalog.modules[0],title:'',days:1},dialog=$('#editor'),revision=catalog.revision||0;dialog.innerHTML=`<h3>강의 ${existing?'수정':'추가'}</h3><form id="lectureForm"><div class="form-grid"><label>과정<select name="course">${catalog.courses.map(x=>option(x,l.course)).join('')}</select></label><label>모듈<select name="module">${catalog.modules.map(x=>option(x,l.module)).join('')}</select></label><label class="full">강의명<input name="title" required maxlength="200" value="${esc(l.title)}"></label><label>총 일차<input name="days" required type="number" min="1" max="100" value="${l.days??''}"></label></div><p id="formError" role="alert"></p><div class="actions"><button id="cancel" type="button">취소</button><button type="submit" class="primary">저장</button></div></form>`;$('#cancel').onclick=()=>dialog.close();$('#lectureForm').onsubmit=async ev=>{ev.preventDefault();const b=ev.target.querySelector('[type="submit"]');b.disabled=true;try{const v=Object.fromEntries(new FormData(ev.target));if(!v.title.trim())throw Error('강의명을 입력해 주세요.');catalog=await store.saveCatalog({...catalog,lectures:[...catalog.lectures.filter(x=>x.id!==l.id),{...l,...v,title:v.title.trim(),days:Number(v.days)}]},revision);planCache=null;dialog.close();message='강의 목록을 저장했습니다. 기존 날짜별 배정은 유지됩니다.';render();}catch(e){$('#formError').textContent=e.message;}finally{b.disabled=false;}};dialog.showModal();}
 function renderInstructors(body){body.innerHTML=`<div class="toolbar"><button id="addInstructor" class="primary">+ 강사 등록</button><span class="muted">연락처·소속·관리 메모는 관리자에게만 표시합니다.</span></div><div class="cards">${Object.entries(instructors).map(([key,v])=>{const assigned=Object.entries(combined()).flatMap(([cid,c])=>c.entries.filter(e=>e.instructorId===key&&e.kind!=='holiday').map(e=>({cid,...e})));return `<section class="card"><h3>${esc(v.name)}</h3><p>${esc(v.organization||'소속 미등록')}<br>${esc(v.phone||'연락처 미등록')}</p><p class="muted">${esc(v.note||'')}</p><button data-instructor="${esc(key)}">정보 수정</button><details><summary>배정 일정 ${assigned.length}건</summary>${sortEntries(assigned).map(e=>`<p class="muted">${esc(e.date)} · ${esc(e.cid)}반 · ${esc(e.title)} ${e.day}일차</p>`).join('')}</details></section>`;}).join('')||'<div class="empty">등록된 강사가 없습니다. 이름과 연락처를 등록한 뒤 시간표에서 배정해 주세요.</div>'}</div>`;$('#addInstructor').onclick=()=>editInstructor();root.querySelectorAll('[data-instructor]').forEach(b=>b.onclick=()=>editInstructor(b.dataset.instructor));}
 function editInstructor(key=id()){const v=instructors[key]||{name:'',organization:'',phone:'',note:'',revision:0},dialog=$('#editor');dialog.innerHTML=`<h3>강사 정보</h3><form id="instructorForm"><div class="form-grid">${[['name','이름'],['organization','소속'],['phone','연락처'],['note','관리 메모']].map(([k,t])=>`<label>${t}<input name="${k}" maxlength="${k==='note'?500:100}" value="${esc(v[k])}" ${k==='name'?'required':''}></label>`).join('')}</div><p id="formError" role="alert"></p><div class="actions"><button id="cancel" type="button">취소</button><button type="submit" class="primary">저장</button></div></form>`;$('#cancel').onclick=()=>dialog.close();$('#instructorForm').onsubmit=async ev=>{ev.preventDefault();const b=ev.target.querySelector('[type="submit"]');b.disabled=true;try{const values=Object.fromEntries(new FormData(ev.target));if(!values.name.trim())throw Error('강사 이름을 입력해 주세요.');instructors[key]=await store.save('instructors',key,values,v.revision||0);message='강사 정보를 저장했습니다. 공개 일정의 강사명 변경은 해당 반을 다시 공개하면 반영됩니다.';dialog.close();render();}catch(e){$('#formError').textContent=e.message;}finally{b.disabled=false;}};dialog.showModal();}
 try{await load();render();}catch(e){content.innerHTML=`<div class="message error">시간표를 불러오지 못했습니다. ${esc(e.message)}</div>`;}
 return {canLeave:leave,dispose(){disposed=true;board.dispose();window.removeEventListener('beforeunload',beforeUnload);}};
}
function renderTeacher(host,entries,meta,{compact=false}={}){
 const root=shell(host),content=root.querySelector('#content');let date=todayKST(),mode='week';
 function render(){const ends=new Set(lectureEndDays(entries).map(e=>e.id));const current=visibleToday(entries),days=mode==='month'?monthDays(date):weekDays(date);
  content.innerHTML=`<section class="today-panel"><div class="eyebrow" style="color:#bbd6f9">MY CLASS · ${esc(meta.id)}반</div><h3>오늘의 수업 <small>${todayKST().slice(5).replace('-','/')} (${weekday(todayKST())})</small></h3>${current.today.length?current.today.map(e=>lesson(e,{},false,meta.id,ends.has(e.id))).join(''):`<p>${entries.length?'오늘은 예정된 수업이 없습니다.':'아직 공개된 시간표가 없습니다.'}</p>${current.next?`<div class="muted">다음 수업 · ${esc(current.next.date)} · ${esc(current.next.title)}</div>`:''}`}</section><section class="teacher-calendar"><div class="top"><h2>우리 반 전체 일정</h2><span class="muted">${esc(meta.course||'')} · ${esc(meta.venue||'')}</span></div><div class="toolbar switch"><button id="week" class="${mode==='week'?'active':''}">주간</button><button id="month" class="${mode==='month'?'active':''}">월간</button><button id="previous" aria-label="이전 기간">‹</button><label>기준 날짜<input id="date" type="date" value="${date}"></label><button id="next" aria-label="다음 기간">›</button><button id="today">오늘</button></div><div class="legend">${[...new Set(entries.map(e=>e.module))].map(m=>`<span style="${paint(m)}">${esc(m)}</span>`).join('')}</div><div class="schedule-scroll"><div class="month-grid">${['월','화','수','목','금','토','일'].map(t=>`<div class="grid-head">${t}</div>`).join('')}${days.map(d=>`<div class="day-cell ${d===todayKST()?'today':''} ${mode==='month'&&d.slice(0,7)!==date.slice(0,7)?'outside':''}"><div class="day-num">${d.slice(5).replace('-','/')}</div>${entries.filter(e=>e.date===d).map(e=>lesson(e,{},false,meta.id,ends.has(e.id))).join('')}</div>`).join('')}</div></div><div class="mobile-list">${days.filter(d=>entries.some(e=>e.date===d)).map(d=>`<section class="card"><h3>${d.slice(5).replace('-','/')} (${weekday(d)})</h3>${entries.filter(e=>e.date===d).map(e=>lesson(e,{},false,meta.id,ends.has(e.id))).join('')}</section>`).join('')||'<div class="empty">선택한 기간의 수업이 없습니다.</div>'}</div></section>`;
  if(compact){root.querySelector('.teacher-calendar')?.remove();return;}
  for(const m of ['week','month'])root.querySelector('#'+m).onclick=()=>{mode=m;render();};root.querySelector('#date').onchange=e=>{if(e.target.value){date=e.target.value;render();}};root.querySelector('#today').onclick=()=>{date=todayKST();render();};for(const [key,delta]of [['previous',-1],['next',1]])root.querySelector('#'+key).onclick=()=>{const d=new Date(date+'T12:00:00Z');if(mode==='month'){d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+delta);}else d.setUTCDate(d.getUTCDate()+7*delta);date=d.toISOString().slice(0,10);render();};
 }render();
}
export async function mountTeacherTimetable(host,{db,user,classInfo,compact=false,includeSurveys=false}){await loadSurveyLinks();const root=shell(host);root.querySelector('#content').innerHTML='<div class="empty">우리 반 시간표를 불러오는 중…</div>';try{const [data,materials]=await Promise.all([createTimetableStore(db,user).read('published',classInfo.id),readMaterials(db,classInfo.id)]);if(host.isConnected){const entries=(data?.entries||[]).map(e=>({...e,materials:materials.filter(m=>m.lectureKey===(e.lectureId||e.title))}));renderTeacher(host,entries,classInfo,{compact});}}catch(e){root.querySelector('#content').innerHTML=`<div class="message error">시간표 조회에 실패했습니다. ${esc(e.message)}</div>`;}}
