import {todayKST,weekDays,monthDays,sortEntries,validateEntry,conflicts,publishEntries,visibleToday} from './timetable-core.mjs';
import {createTimetableStore} from './timetable-store.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const palette={'동기부여':['#8864bb','#f4effb'],'디지털스킬':['#326ac0','#edf3fc'],'소프트스킬':['#4291a4','#edf7f9'],'직무특화':['#28685e','#ecf6f1'],'공장견학':['#b67726','#fff5e7'],'문화체험':['#bc5b80','#fceff4'],'진로탐색':['#5d67aa','#f0f0fc'],'현직자특강':['#be713a','#fff2e9'],'실차체험':['#548752','#f0f7ec'],'공통행사':['#a26148','#faf0ec'],'휴일':['#82909f','#f1f3f6']};
const paint=m=>{const c=palette[m]||['#65748b','#f0f4f8'];return `--module:${c[0]};--tint:${c[1]}`;};
const option=(value,selected,label=value)=>`<option value="${esc(value)}" ${value===selected?'selected':''}>${esc(label)}</option>`;
const weekday=d=>new Intl.DateTimeFormat('ko-KR',{weekday:'short',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
const id=()=>crypto.randomUUID();
function lesson(e,instructors={},click=false,cid=''){
 const name=e.instructorName||instructors[e.instructorId]?.name||'',time=e.start?`${e.start}–${e.end}`:e.hours?`${e.hours}시간 · 시각 미등록`:'';
 return `<${click?'button':'article'} class="lesson" style="${paint(e.module)}" ${click?`data-edit="${esc(e.id)}" data-cid="${esc(cid)}" aria-label="${esc(cid+'반 '+e.date+' '+e.title+' 수정')}"`:''}><small>${esc(e.module)}${e.online?' · 비대면':''}</small><strong>${esc(e.title)}${e.day?' · '+e.day+'일차':''}</strong><small>${esc(time)}</small>${e.kind==='holiday'?'':`<small>${esc(name||'강사 미등록')}${e.venue?' · '+esc(e.venue):''}</small>`}${e.note?`<small>${esc(e.note)}</small>`:''}</${click?'button':'article'}>`;
}
function shell(host){const root=host.shadowRoot||host.attachShadow({mode:'open'});root.innerHTML='<link rel="stylesheet" href="/timetable.css?v=20260911-1"><div id="content"></div><dialog id="editor"></dialog>';return root;}
export async function mountTimetableAdmin(host,{db,user,classes}){
 const root=shell(host),store=createTimetableStore(db,user),$=s=>root.querySelector(s),content=$('#content');
 let seed,catalog,drafts={},published={},instructors={},selected='all',date=todayKST(),mode='schedule',busy=false,message='',error=false;
 const meta=cid=>classes.find(c=>String(c.id)===String(cid))||{id:cid};
 content.innerHTML='<div class="empty">시간표와 강사 정보를 불러오는 중…</div>';
 async function load(){const r=await fetch('/timetable-seed.json');if(!r.ok)throw Error('기준 엑셀 일정을 읽지 못했습니다.');seed=await r.json();[catalog,drafts,published,instructors]=await Promise.all([store.catalog(seed),store.all('draft'),store.all('published'),store.all('instructors')]);}
 const data=cid=>drafts[cid]||seed.classes[cid]||{entries:[],revision:0};
 const combined=()=>Object.fromEntries(classes.map(c=>[c.id,data(c.id)]));
 async function action(fn){if(busy)return;busy=true;message='처리 중…';error=false;render();try{await fn();}catch(e){message=e.message;error=true;}finally{busy=false;if(host.isConnected)render();}}
 function render(){
  const shown=selected==='all'?classes:classes.filter(c=>String(c.id)===selected),days=weekDays(date);
  content.innerHTML=`<div class="top"><div><div class="eyebrow">HINT / TIMETABLE BETA</div><h2>시간표 관리</h2><div class="muted">엑셀 기준 일정 → 편집본 저장 → 담임에게 공개. 강사 연락처는 관리자만 확인합니다.</div></div><div class="actions"><button id="reload">↻ 새로고침</button><button id="import">엑셀 기준 17개 반 가져오기</button></div></div><div class="toolbar switch">${[['schedule','반별 시간표'],['catalog','과정·강의 관리'],['instructors','강사 관리'],['preview','담임 화면 미리보기']].map(([v,t])=>`<button data-mode="${v}" class="${mode===v?'active':''}">${t}</button>`).join('')}</div>${message?`<div role="status" class="message ${error?'error':''}">${esc(message)}</div>`:''}<div id="body"></div>`;
  const body=$('#body');
  if(mode==='schedule'){
   body.innerHTML=`<div class="toolbar"><label>반<select id="classFilter">${option('all',selected,'전체 17개 반')}${classes.map(c=>option(String(c.id),selected,`${c.id}반 · ${c.course}`)).join('')}</select></label><button id="previous" aria-label="지난주">‹</button><label>기준 날짜<input id="date" type="date" value="${date}"></label><button id="next" aria-label="다음주">›</button><button id="today">오늘</button><button id="new">+ 일정 추가</button><button class="primary" id="publish">${selected==='all'?'17개 반':'선택 반'} 담임에게 공개</button></div><div class="legend">${catalog.modules.map(m=>`<span style="${paint(m)}">${esc(m)}</span>`).join('')}</div><div class="schedule-scroll"><div class="admin-grid"><div class="grid-head">반 / 교육일</div>${days.map(d=>`<div class="grid-head">${d.slice(5).replace('-','/')} (${weekday(d)})${d===todayKST()?' · 오늘':''}</div>`).join('')}${shown.map(c=>`<div class="class-label"><b>${c.id}반</b><div class="muted">${esc(c.course)}<br>${esc(c.venue||'')}</div><div class="board-status">${!drafts[c.id]?'<span class="dirty">엑셀 미저장</span>':published[c.id]?.sourceRevision===drafts[c.id]?.revision?'✓ 공개됨':'<span class="dirty">공개 전 변경</span>'}</div></div>${days.map(d=>`<div class="day-cell ${d===todayKST()?'today':''}">${sortEntries(data(c.id).entries).filter(e=>e.date===d).map(e=>lesson(e,instructors,true,c.id)).join('')}<button class="add" data-add="${d}" data-cid="${c.id}">+ 추가</button></div>`).join('')}`).join('')}</div></div>`;
   $('#classFilter').onchange=e=>{selected=e.target.value;render();};$('#date').onchange=e=>{if(e.target.value){date=e.target.value;render();}};$('#today').onclick=()=>{date=todayKST();render();};
   for(const [key,delta] of [['previous',-7],['next',7]])$('#'+key).onclick=()=>{const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+delta);date=d.toISOString().slice(0,10);render();};
   $('#new').onclick=()=>editEntry(selected==='all'?'1':selected,null,date);
   root.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>editEntry(b.dataset.cid,null,b.dataset.add));
   root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editEntry(b.dataset.cid,data(b.dataset.cid).entries.find(e=>e.id===b.dataset.edit)));
   $('#publish').onclick=()=>{const targets=shown.filter(c=>drafts[c.id]);if(!targets.length){message='먼저 엑셀 기준 일정을 가져오거나 편집본을 저장해 주세요.';render();return;}if(!confirm(`${targets.length}개 반의 저장된 편집본을 담임에게 공개할까요?`))return;action(async()=>{let count=0;for(const c of targets){published[c.id]=await store.publish(String(c.id),drafts[c.id],published[c.id]?.revision||0,publishEntries(drafts[c.id].entries,instructors));count++;message=`${count}/${targets.length}개 반 공개 완료`;}});};
  }else if(mode==='catalog')renderCatalog(body);
  else if(mode==='instructors')renderInstructors(body);
  else {const cid=selected==='all'?'1':selected;body.innerHTML=`<div class="toolbar"><label>미리볼 반<select id="previewClass">${classes.map(c=>option(String(c.id),cid,`${c.id}반 · ${c.course}`)).join('')}</select></label><span class="muted">담임에게 공개한 일정만 표시합니다.</span></div><div id="preview"></div>`;$('#previewClass').onchange=e=>{selected=e.target.value;render();};renderTeacher($('#preview'),published[cid]?.entries||[],meta(cid));}
  root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render();});
  $('#reload').onclick=()=>action(async()=>{await load();message='최신 시간표를 읽었습니다.';});
  $('#import').onclick=()=>{const targets=classes.filter(c=>!drafts[c.id]);if(!targets.length){message='17개 반의 편집본이 이미 있습니다. 기존 일정은 유지됩니다.';render();return;}if(!confirm(`편집본이 없는 ${targets.length}개 반에 엑셀 일정을 가져올까요? 기존 편집본과 원본 엑셀은 유지됩니다.`))return;action(async()=>{let n=0;for(const c of targets){drafts[c.id]=await store.save('draft',c.id,{classId:String(c.id),entries:seed.classes[c.id].entries},0);message=`${++n}/${targets.length}개 반 가져오기 완료 · 확인 후 담임에게 공개해 주세요.`;}});};
  if(busy)root.querySelectorAll('button,input,select').forEach(b=>b.disabled=true);
 }
 function editEntry(cid,entry,targetDate=date){
  const base=data(cid),expected=base.revision||0,defaults=catalog.lectures.find(l=>l.course===(meta(cid).course?.startsWith('제조')?'제조지능화':meta(cid).course))||catalog.lectures[0];
  const e=entry?{...entry}:{id:id(),date:targetDate,...defaults,lectureId:defaults.id,day:1,hours:8,start:'',end:'',instructorId:'',venue:meta(cid).venue||'',note:'',online:false,kind:'class'};
  if(!entry)e.id=id();const dialog=$('#editor');
  dialog.innerHTML=`<h3>${cid}반 · ${entry?'수업 수정':'일정 추가'}</h3><form id="entryForm"><div class="form-grid"><label>교육일자<input name="date" type="date" value="${e.date}" required></label><label>과정<select name="course">${catalog.courses.map(x=>option(x,e.course)).join('')}</select></label><label>모듈<select name="module"></select></label><label>강의<select name="lectureId"></select></label><label>강의 일차<input name="day" type="number" min="1" max="100" value="${e.day||1}" required></label><label>교육시간 (시간)<input name="hours" type="number" min="0" max="24" step="0.5" value="${e.hours||0}"></label><label>시작 시각<input name="start" type="time" value="${e.start||''}"></label><label>종료 시각<input name="end" type="time" value="${e.end||''}"></label><label>강사<select name="instructorId" aria-label="강사">${option('',e.instructorId,'미등록')}${Object.entries(instructors).map(([k,v])=>option(k,e.instructorId,v.name)).join('')}</select></label><label>장소<input name="venue" value="${esc(e.venue||'')}" maxlength="200"></label><label>일정 구분<select name="kind">${option('class',e.kind,'수업·행사')}${option('holiday',e.kind,'휴일·휴강')}</select></label><label>방식<select name="online">${option('false',String(e.online),'대면')}${option('true',String(e.online),'비대면')}</select></label><label class="full">전달사항<textarea name="note" maxlength="1000">${esc(e.note||'')}</textarea></label></div><div class="batch"><label><span><input name="sameLecture" type="checkbox"> 이 반의 같은 강의 전체 일차에 강사·장소 함께 적용</span></label><label style="margin-top:10px">이 일정을 다른 반에도 복사 (선택)<select name="copyTo"><option value="">복사 안 함</option>${classes.filter(c=>String(c.id)!==cid).map(c=>option(String(c.id),'',c.id+'반')).join('')}</select></label></div><p id="formError" role="alert" class="muted"></p><div class="actions"><button type="button" id="cancel">취소</button><button type="submit" class="primary">편집본 저장</button></div></form>`;
  const f=$('#entryForm'),el=n=>f.elements.namedItem(n);
  function lectures(wanted=e.lectureId){const list=catalog.lectures.filter(l=>l.course===el('course').value&&l.module===el('module').value);el('lectureId').innerHTML=list.map(l=>option(l.id,wanted,l.title)).join('')||'<option value="">강의 관리에서 먼저 등록</option>';}
  function modules(wanted=e.module){const list=[...new Set(catalog.lectures.filter(l=>l.course===el('course').value).map(l=>l.module))];el('module').innerHTML=list.map(m=>option(m,wanted)).join('');lectures();}
  modules();el('course').onchange=()=>modules();el('module').onchange=()=>lectures();
  // Imported holidays retain their label, without inventing a lecture or a teaching day.
  if(e.kind==='holiday'){el('module').innerHTML+=option('휴일','휴일');el('module').value='휴일';el('lectureId').innerHTML=option('', '', e.title);}
  $('#cancel').onclick=()=>dialog.close();
  f.onsubmit=async event=>{event.preventDefault();const button=f.querySelector('[type="submit"]');button.disabled=true;try{
   const v=Object.fromEntries(new FormData(f)),l=catalog.lectures.find(l=>l.id===v.lectureId);if(!l&&v.kind!=='holiday')throw Error('강의를 먼저 선택해 주세요.');
   const next=validateEntry({...e,date:v.date,course:v.course,module:v.kind==='holiday'?'휴일':v.module,lectureId:v.lectureId,title:l?.title||e.title,day:v.kind==='holiday'?0:Number(v.day),hours:Number(v.hours),start:v.start,end:v.end,instructorId:v.instructorId,venue:v.venue,note:v.note,online:v.online==='true',kind:v.kind});
   const clash=conflicts(next,combined(),cid);if(clash.length&&!confirm(`같은 강사의 일정이 겹치거나 시각 확인이 필요합니다.\n${clash.map(x=>x.classId+'반 '+x.date+' '+x.title).join('\n')}\n그래도 저장할까요?`))return;
   let entries=base.entries.filter(x=>x.id!==next.id);entries.push(next);if(v.sameLecture)entries=entries.map(x=>x.lectureId===next.lectureId&&x.kind!=='holiday'?{...x,instructorId:next.instructorId,venue:next.venue}:x);
   const changes=[{classId:cid,entries:sortEntries(entries),revision:expected}];
   if(v.copyTo){const other=data(v.copyTo),copy={...next,id:id()};changes.push({classId:v.copyTo,entries:sortEntries([...other.entries,copy]),revision:other.revision||0});}
   drafts={...drafts,...await store.saveDrafts(changes)};
   message='편집본을 저장했습니다. 확인 후 담임에게 공개해 주세요.';error=false;dialog.close();render();
  }catch(err){$('#formError').textContent=err.message;}finally{button.disabled=false;}};dialog.showModal();
 }
 function renderCatalog(body){
  body.innerHTML=`<div class="toolbar"><button id="addCourse">+ 과정</button><button id="addModule">+ 모듈</button><button id="addLecture" class="primary">+ 강의</button><span class="muted">과정 → 모듈 → 강의 → 일차. 목록 수정이 기존 반 일정을 바꾸지는 않습니다.</span></div><div class="chips">${catalog.courses.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><div class="cards">${catalog.courses.map(course=>`<section class="card"><h3>${esc(course)}</h3>${catalog.modules.map(m=>{const ls=catalog.lectures.filter(l=>l.course===course&&l.module===m);return ls.length?`<h4>${esc(m)}</h4>${ls.map(l=>`<button style="display:block;width:100%;margin:6px 0;text-align:left" data-lecture="${esc(l.id)}">${esc(l.title)} <small>· ${l.days}일</small></button>`).join('')}`:'';}).join('')}</section>`).join('')}</div>`;
  for(const [key,field,label] of [['addCourse','courses','과정'],['addModule','modules','모듈']])$('#'+key).onclick=()=>{const name=prompt(`추가할 ${label} 이름`);if(!name?.trim())return;action(async()=>{if(name.length>80)throw Error('이름은 80자 이내로 입력해 주세요.');catalog=await store.saveCatalog({...catalog,[field]:[...new Set([...catalog[field],name.trim()])]},catalog.revision||0);message=label+'을 추가했습니다.';});};
  $('#addLecture').onclick=()=>editLecture();root.querySelectorAll('[data-lecture]').forEach(b=>b.onclick=()=>editLecture(catalog.lectures.find(l=>l.id===b.dataset.lecture)));
 }
 function editLecture(existing){const l=existing||{id:id(),course:catalog.courses[0],module:catalog.modules[0],title:'',days:1},dialog=$('#editor'),revision=catalog.revision||0;dialog.innerHTML=`<h3>강의 ${existing?'수정':'추가'}</h3><form id="lectureForm"><div class="form-grid"><label>과정<select name="course">${catalog.courses.map(x=>option(x,l.course)).join('')}</select></label><label>모듈<select name="module">${catalog.modules.map(x=>option(x,l.module)).join('')}</select></label><label class="full">강의명<input name="title" required maxlength="200" value="${esc(l.title)}"></label><label>총 일차<input name="days" required type="number" min="1" max="100" value="${l.days}"></label></div><p id="formError" role="alert"></p><div class="actions"><button id="cancel" type="button">취소</button><button type="submit" class="primary">저장</button></div></form>`;$('#cancel').onclick=()=>dialog.close();$('#lectureForm').onsubmit=async ev=>{ev.preventDefault();const b=ev.target.querySelector('[type="submit"]');b.disabled=true;try{const v=Object.fromEntries(new FormData(ev.target));if(!v.title.trim())throw Error('강의명을 입력해 주세요.');catalog=await store.saveCatalog({...catalog,lectures:[...catalog.lectures.filter(x=>x.id!==l.id),{...l,...v,title:v.title.trim(),days:Number(v.days)}]},revision);dialog.close();message='강의 목록을 저장했습니다. 기존 날짜별 배정은 유지됩니다.';render();}catch(e){$('#formError').textContent=e.message;}finally{b.disabled=false;}};dialog.showModal();}
 function renderInstructors(body){body.innerHTML=`<div class="toolbar"><button id="addInstructor" class="primary">+ 강사 등록</button><span class="muted">연락처·소속·관리 메모는 관리자에게만 표시합니다.</span></div><div class="cards">${Object.entries(instructors).map(([key,v])=>{const assigned=Object.entries(combined()).flatMap(([cid,c])=>c.entries.filter(e=>e.instructorId===key&&e.kind!=='holiday').map(e=>({cid,...e})));return `<section class="card"><h3>${esc(v.name)}</h3><p>${esc(v.organization||'소속 미등록')}<br>${esc(v.phone||'연락처 미등록')}</p><p class="muted">${esc(v.note||'')}</p><button data-instructor="${esc(key)}">정보 수정</button><details><summary>배정 일정 ${assigned.length}건</summary>${sortEntries(assigned).map(e=>`<p class="muted">${esc(e.date)} · ${esc(e.cid)}반 · ${esc(e.title)} ${e.day}일차</p>`).join('')}</details></section>`;}).join('')||'<div class="empty">등록된 강사가 없습니다. 이름과 연락처를 등록한 뒤 시간표에서 배정해 주세요.</div>'}</div>`;$('#addInstructor').onclick=()=>editInstructor();root.querySelectorAll('[data-instructor]').forEach(b=>b.onclick=()=>editInstructor(b.dataset.instructor));}
 function editInstructor(key=id()){const v=instructors[key]||{name:'',organization:'',phone:'',note:'',revision:0},dialog=$('#editor');dialog.innerHTML=`<h3>강사 정보</h3><form id="instructorForm"><div class="form-grid">${[['name','이름'],['organization','소속'],['phone','연락처'],['note','관리 메모']].map(([k,t])=>`<label>${t}<input name="${k}" maxlength="${k==='note'?500:100}" value="${esc(v[k])}" ${k==='name'?'required':''}></label>`).join('')}</div><p id="formError" role="alert"></p><div class="actions"><button id="cancel" type="button">취소</button><button type="submit" class="primary">저장</button></div></form>`;$('#cancel').onclick=()=>dialog.close();$('#instructorForm').onsubmit=async ev=>{ev.preventDefault();const b=ev.target.querySelector('[type="submit"]');b.disabled=true;try{const values=Object.fromEntries(new FormData(ev.target));if(!values.name.trim())throw Error('강사 이름을 입력해 주세요.');instructors[key]=await store.save('instructors',key,values,v.revision||0);message='강사 정보를 저장했습니다. 공개 일정의 강사명 변경은 해당 반을 다시 공개하면 반영됩니다.';dialog.close();render();}catch(e){$('#formError').textContent=e.message;}finally{b.disabled=false;}};dialog.showModal();}
 try{await load();render();}catch(e){content.innerHTML=`<div class="message error">시간표를 불러오지 못했습니다. ${esc(e.message)}</div>`;}
}
function renderTeacher(host,entries,meta){
 const root=shell(host),content=root.querySelector('#content');let date=todayKST(),mode='week';
 function render(){const current=visibleToday(entries),days=mode==='month'?monthDays(date):weekDays(date);
  content.innerHTML=`<section class="today-panel"><div class="eyebrow" style="color:#bbd6f9">MY CLASS · ${esc(meta.id)}반</div><h3>오늘의 수업 <small>${todayKST().slice(5).replace('-','/')} (${weekday(todayKST())})</small></h3>${current.today.length?current.today.map(e=>lesson(e)).join(''):`<p>${entries.length?'오늘은 예정된 수업이 없습니다.':'아직 공개된 시간표가 없습니다.'}</p>${current.next?`<div class="muted">다음 수업 · ${esc(current.next.date)} · ${esc(current.next.title)}</div>`:''}`}</section><section class="teacher-calendar"><div class="top"><h2>우리 반 전체 일정</h2><span class="muted">${esc(meta.course||'')} · ${esc(meta.venue||'')}</span></div><div class="toolbar switch"><button id="week" class="${mode==='week'?'active':''}">주간</button><button id="month" class="${mode==='month'?'active':''}">월간</button><button id="previous" aria-label="이전 기간">‹</button><label>기준 날짜<input id="date" type="date" value="${date}"></label><button id="next" aria-label="다음 기간">›</button><button id="today">오늘</button></div><div class="legend">${[...new Set(entries.map(e=>e.module))].map(m=>`<span style="${paint(m)}">${esc(m)}</span>`).join('')}</div><div class="schedule-scroll"><div class="month-grid">${['월','화','수','목','금','토','일'].map(t=>`<div class="grid-head">${t}</div>`).join('')}${days.map(d=>`<div class="day-cell ${d===todayKST()?'today':''} ${mode==='month'&&d.slice(0,7)!==date.slice(0,7)?'outside':''}"><div class="day-num">${d.slice(5).replace('-','/')}</div>${entries.filter(e=>e.date===d).map(e=>lesson(e)).join('')}</div>`).join('')}</div></div><div class="mobile-list">${days.filter(d=>entries.some(e=>e.date===d)).map(d=>`<section class="card"><h3>${d.slice(5).replace('-','/')} (${weekday(d)})</h3>${entries.filter(e=>e.date===d).map(e=>lesson(e)).join('')}</section>`).join('')||'<div class="empty">선택한 기간의 수업이 없습니다.</div>'}</div></section>`;
  for(const m of ['week','month'])root.querySelector('#'+m).onclick=()=>{mode=m;render();};root.querySelector('#date').onchange=e=>{if(e.target.value){date=e.target.value;render();}};root.querySelector('#today').onclick=()=>{date=todayKST();render();};for(const [key,delta]of [['previous',-1],['next',1]])root.querySelector('#'+key).onclick=()=>{const d=new Date(date+'T12:00:00Z');if(mode==='month'){d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+delta);}else d.setUTCDate(d.getUTCDate()+7*delta);date=d.toISOString().slice(0,10);render();};
 }render();
}
export async function mountTeacherTimetable(host,{db,user,classInfo}){const root=shell(host);root.querySelector('#content').innerHTML='<div class="empty">우리 반 시간표를 불러오는 중…</div>';try{const data=await createTimetableStore(db,user).read('published',classInfo.id);if(host.isConnected)renderTeacher(host,data?.entries||[],classInfo);}catch(e){root.querySelector('#content').innerHTML=`<div class="message error">시간표 조회에 실패했습니다. ${esc(e.message)}</div>`;}}
