import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {resolve,sep} from 'node:path';import {loadPlaywright} from '../collector.mjs';
test('only connected designated approver auto-confirms matching rows; database failure never shows already-applied completion',async()=>{
 const {chromium}=loadPlaywright(),browser=await chromium.launch({channel:'chrome',headless:true}),base=resolve(import.meta.dirname,'../..');
 try{for(const mode of ['approver','staff','old','db-failure']){
  const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',route=>{
   const u=new URL(route.request().url());
   if(u.hostname==='www.gstatic.com')return route.fulfill({contentType:'text/javascript',body:`export const collection=(...x)=>x,doc=(...x)=>x,query=(...x)=>x,where=(...x)=>x,orderBy=(...x)=>x,limit=x=>x,serverTimestamp=()=>({seconds:1});export const getDoc=(...x)=>getDocFromServer(...x);export async function getDocFromServer(){return{data:()=>undefined};}export async function getDocs(){return{docs:window.rows.map(r=>({id:r.id,data:()=>r}))};}export async function setDoc(){throw Error('no new requests');}export async function runTransaction(){throw Error('approval belongs to collector');}`});
   if(u.pathname==='/')return route.fulfill({contentType:'text/html; charset=utf-8',body:`<div id="host"></div><script type="module">import {mountCheckHereRequests} from '/checkhere-requests.mjs';window.rows=[{id:'already-fixture',classId:'2',date:'2026-09-14',name:'가상학생',phoneLast4:'1234',reason:'가상 검증',changes:{entryMemo:''},status:'pending'}];window.calls=[];const r={id:'record-fixture',version:'v1',classId:'2',date:'2026-09-14',name:'가상학생',phoneLast4:'1234',source:'live',readState:'complete',entry:'09:00:00',exit:'18:00:00',entryMemo:'',exitMemo:''};const c={state:()=>({connected:true,records:[r],jobs:[{id:'already-fixture',status:'verified'}],capabilities:['${mode==='old'?'approved-requests-v1':'approval-current-sync-v1'}']}),refresh:async()=>{},api:async(path)=>{window.calls.push(path);if(path==='confirm-existing')return{status:'running'};if(path==='reconcile'){if('${mode}'==='db-failure')return{status:'verified',platformSaved:false};window.rows[0].status='verified';window.rows[0].result={alreadyApplied:true,platformSaved:true};return{status:'verified',alreadyApplied:true,platformSaved:true};}throw Error('unexpected write');}};window.ui=await mountCheckHereRequests(document.querySelector('#host'),{db:{},user:{email:'${mode==='staff'?'other@example.com':'hint.kpc@gmail.com'}',getIdTokenResult:async()=>({claims:{firebase:{sign_in_provider:'google.com'}}}),getIdToken:async()=>'fixture'},classes:[{id:'2'}],admin:true,controller:()=>c});window.ready=true;</script>`});
   const path=resolve(base,u.pathname.slice(1));if(path.startsWith(base+sep)&&existsSync(path)&&/\.(mjs|json|css)$/.test(path))return route.fulfill({contentType:'text/javascript',body:readFileSync(path,'utf8')});return route.abort();
  });
  await page.goto('https://fixture.test/');await page.waitForFunction(()=>window.ready,{},{timeout:10000}).catch(e=>{throw Error(e.message+' '+errors.join(';'));});assert.deepEqual(errors,[]);
  if(mode==='approver'){assert.equal(await page.getByText('이미 반영',{exact:true}).count(),1);assert.deepEqual(await page.evaluate(()=>window.calls),['confirm-existing','reconcile']);}
  else if(mode==='db-failure'){assert.equal(await page.getByText('이미 반영',{exact:true}).count(),0);assert.match(await page.locator('#message').innerText(),/DB 저장은 아직 완료되지 않았/);}
  else assert.deepEqual(await page.evaluate(()=>window.calls),[]);
  await page.evaluate(()=>window.ui.refresh());assert.equal(await page.evaluate(()=>window.calls.filter(x=>x==='confirm-existing').length),['approver','db-failure'].includes(mode)?1:0,'no repeated remote checks for unchanged snapshots');await page.close();
 }}finally{await browser.close();}
});
