import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {join} from 'node:path';import {loadPlaywright} from '../collector.mjs';
test('column approval waits for verified completion, preserves other fields, filters scope and stops on failure',async()=>{
 const {chromium}=loadPlaywright(),browser=await chromium.launch({channel:'chrome',headless:true}),base=join(import.meta.dirname,'../..');
 try{for(const fail of [false,true]){
  const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',route=>{
   const u=new URL(route.request().url());
   if(u.hostname==='www.gstatic.com')return route.fulfill({contentType:'text/javascript',body:`export const collection=(...x)=>x,doc=(...x)=>({id:x.at(-1)}),query=(...x)=>x,where=(...x)=>x,orderBy=(...x)=>x,limit=x=>x,serverTimestamp=()=>({seconds:1});export const getDocFromServer=(...a)=>getDoc(...a);export async function getDoc(){return{data:()=>undefined};}export async function setDoc(){}export async function getDocs(){return{docs:window.rows.map(r=>({id:r.id,data:()=>r}))};}export async function runTransaction(db,fn){return fn({get:async ref=>({data:()=>window.rows.find(r=>r.id===ref.id)}),update(ref,data){Object.assign(window.rows.find(r=>r.id===ref.id),data);}});}`});
   if(u.pathname==='/')return route.fulfill({contentType:'text/html; charset=utf-8',body:`<div id="host"></div><script type="module">import {mountCheckHereRequests} from '/checkhere-requests.mjs';const common={classId:'2',date:'2026-09-03',phoneLast4:'1234',reason:'수기 확인',status:'pending',createdAt:{seconds:1}};window.rows=[{...common,id:'time-a',name:'가상가',changes:{entry:'09:00:00'}},{...common,id:'memo-a',name:'가상가',changes:{entryMemo:'가상가 사유'}},{...common,id:'memo-b',name:'가상나',changes:{entryMemo:'가상나 사유'}},{...common,id:'exit-a',name:'가상가',changes:{exitMemo:'퇴실 사유'}},{...common,classId:'3',id:'other-class',name:'다른반',changes:{entryMemo:'범위 제외'}}];window.records=['가상가','가상나'].map((name,i)=>({...common,id:'record-'+i,name,version:'v1',teacher:'홍길동',source:'live',readState:'complete',schedule:'09:00 ~ 18:00',entry:'13:00:00',exit:'18:00:00',entryMemo:'기존',exitMemo:'',outings:[]}));window.calls=[];const jobs=[];let current=null,ticks=0;const controller={state:()=>({records:window.records,jobs,capabilities:['approved-requests-v1']}),refresh:async()=>{if(current&&++ticks>=2){const job=jobs.find(j=>j.id===current.id);job.status=${fail}?'failed':'verified';job.message=${fail}?'저장 실패 시험':'검증됨';if(!${fail})Object.assign(window.records.find(r=>r.name===current.name),current.approval.after,{version:'v'+(jobs.length+1)});else current.status='failed';current=null;}},api:async(path,input)=>{const r=window.rows.find(r=>r.id===input.approvalId);window.calls.push({path,id:r.id});if(path==='apply'){if(current)throw Error('동시 반영 금지');if(r.status!=='approved')throw Error('승인 안 됨');current=r;ticks=0;r.status='applying';jobs.push({id:r.id,status:'running'});return{};}if(path==='reconcile'){r.status='verified';return{status:'verified'};}}};window.ui=await mountCheckHereRequests(document.querySelector('#host'),{db:{},user:{email:'hint.kpc@gmail.com',getIdTokenResult:async()=>({claims:{firebase:{sign_in_provider:'google.com'}}}),getIdToken:async()=>'fixture'},classes:[{id:'2'},{id:'3'}],admin:true,controller:()=>controller});</script>`});
   if(['attendance-io.mjs','checkhere-requests.mjs','checkhere/approval-core.mjs','checkhere/rules.mjs','attendance-beta-core.mjs','checkhere-request-actions.mjs','timetable-core.mjs','checkhere-proposals.mjs','attendance-reason-parser.mjs','checkhere-proposal-core.mjs'].includes(u.pathname.slice(1)))return route.fulfill({contentType:'text/javascript',body:readFileSync(join(base,u.pathname.slice(1)),'utf8')});return route.abort();
  });
  await page.goto('https://fixture.test/');await page.locator('#requestClass').selectOption('2');await page.locator('#requestDate').fill('2026-09-03');
  const approve=async(column,count)=>{await page.locator(`[data-bulk-approve="${column}"]`).click();await page.locator('#bulkApproveNow').waitFor();assert.match(await page.locator('#bulkApproveNow').innerText(),new RegExp(count+'건'));const before=await page.evaluate(()=>window.calls.length);await page.locator('#bulkApproveNow').click();await page.locator('#batchResult').filter({hasText:fail?'오류가 발생해 나머지 반영을 중단':'검증 완료 '+count+'건 / '+count+'건'}).waitFor();assert((await page.evaluate(()=>window.calls.length))>before);await page.locator('#batchClose').click();};
  if(fail){await approve('entryMemo',2);const result=await page.evaluate(()=>({calls:window.calls,rows:window.rows}));assert.deepEqual(result.calls.map(x=>x.id),['memo-a']);assert.equal(result.rows.find(r=>r.id==='memo-b').status,'pending');}
  else{
   await approve('times',1);await approve('entryMemo',2);await approve('exitMemo',1);
   const result=await page.evaluate(()=>({calls:window.calls,records:window.records,rows:window.rows}));assert.deepEqual(result.calls.map(x=>x.path),['apply','reconcile','apply','reconcile','apply','reconcile','apply','reconcile']);assert.equal(result.records[0].entry,'09:00:00');assert.equal(result.records[0].entryMemo,'가상가 사유');assert.equal(result.records[0].exitMemo,'퇴실 사유');assert.equal(result.rows.find(r=>r.id==='other-class').status,'pending');
  }
  assert.deepEqual(errors,[]);await page.close();
 }}finally{await browser.close();}
});
