import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {resolve,sep} from 'node:path';import {loadPlaywright} from '../collector.mjs';
test('pending birth-year requests share one class read and preview automatically collected distinct students',async()=>{
 const {chromium}=loadPlaywright(),browser=await chromium.launch({channel:'chrome',headless:true}),base=resolve(import.meta.dirname,'../..'),page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.route('**/*',route=>{
   const u=new URL(route.request().url());
   if(u.hostname==='www.gstatic.com')return route.fulfill({contentType:'text/javascript',body:`export const collection=(...x)=>x,doc=(...x)=>({path:x.slice(1).join('/')}),query=(...x)=>x,where=(...x)=>x,orderBy=(...x)=>x,limit=x=>x,serverTimestamp=()=>({seconds:1});export async function getDoc(ref){if(ref.path!=='classes/9')throw Error('unexpected read');window.classReads++;return{data:()=>({surveyDuplicateIdentities:window.identities})};}export const getDocFromServer=getDoc;export async function getDocs(){return{docs:window.rows.map(r=>({id:r.id,data:()=>r}))};}export async function setDoc(){throw Error('not a request submission');}export async function runTransaction(){throw Error('preview must not approve');}`});
   if(u.pathname==='/')return route.fulfill({contentType:'text/html; charset=utf-8',body:`<div id="host"></div><script type="module">import {mountCheckHereRequests} from '/checkhere-requests.mjs';window.identities=[{name:'가상학생(99년생)',phoneLast4:'1111'},{name:'가상학생(02년생)',phoneLast4:'2222'}];window.classReads=0;window.records=[];window.calls=[];window.rows=identities.map((s,i)=>({id:'request-'+i,classId:'9',date:'2026-08-28',name:s.name,phoneLast4:'',changes:{entryMemo:'새 사유 '+i},reason:'가상 확인',status:'pending'}));const c={state:()=>({connected:true,records:window.records,capabilities:['approval-current-sync-v1','live-approval-preview-v1']}),refresh:async()=>{},api:async(path,{approvalId})=>{window.calls.push(path);if(path!=='preview-request')throw Error('preview only');const i=Number(approvalId.at(-1));const record={id:'record-'+i,studentKey:'key-'+i,version:'v1',classId:'9',date:'2026-08-28',name:'가상학생',phoneLast4:identities[i].phoneLast4,source:'live',readState:'complete',teacher:'가상',entry:'09:00:00',exit:'18:00:00',entryMemo:'기존 '+i,exitMemo:'',outings:[],outingCount:0,schedule:'09:00 ~ 18:00'};window.records.push(record);return{record};}};window.ui=await mountCheckHereRequests(document.querySelector('#host'),{db:{},user:{email:'hint.kpc@gmail.com',getIdTokenResult:async()=>({claims:{firebase:{sign_in_provider:'google.com'}}}),getIdToken:async()=>'fixture'},classes:[{id:'9'}],admin:true,controller:()=>c});window.ready=true;</script>`});
   const file=resolve(base,u.pathname.slice(1));if(file.startsWith(base+sep)&&existsSync(file)&&/\.(mjs|json|css)$/.test(file))return route.fulfill({contentType:'text/javascript',body:readFileSync(file,'utf8')});return route.abort();
  });
  await page.goto('https://fixture.test/');await page.waitForFunction(()=>window.ready);
  for(const i of [1,0]){await page.locator('[data-review="request-'+i+'"]').click();await page.locator('#approve').waitFor();const text=await page.locator('#review').innerText();assert(text.includes('기존 '+i));assert(text.includes('새 사유 '+i));await page.locator('#close').click();}
  await page.evaluate(()=>window.ui.refresh());assert.equal(await page.evaluate(()=>window.classReads),1);assert.deepEqual(await page.evaluate(()=>window.calls),['preview-request','preview-request']);assert.deepEqual(errors,[]);await page.evaluate(()=>window.ui.dispose());
 }finally{await browser.close();}
});
