import test from 'node:test';import assert from 'node:assert/strict';import {loadPlaywright,CheckHereCollector} from '../collector.mjs';
test('real DOM adapter reads both memos and outings; writes only Change',async()=>{
  const {chromium}=loadPlaywright(),browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage();
  try{
    await page.setContent(`<!doctype html><html><body><table><tr><td>대상자</td></tr><tr><td></td><td>순번</td><td>성명</td><td>전화번호</td><td>메모</td></tr><tr><td></td><td>1</td><td>가상학생</td><td>01000000001</td><td>시험</td></tr><tr><td>출석인원</td></tr></table><table><tr><td>강의시간</td></tr><tr><td>입실</td><td>09:00 ~ 18:00</td><td>퇴실</td><td>총 외출 시간(외출횟수)</td><td>총 강의 참여 시간</td></tr><tr><td>09:00:00</td><td onclick="edit('entry')">09:00:00</td><td onclick="edit('exit')">18:00:00</td><td onclick="outing()">30분 (1)</td><td>8시간</td></tr><tr><td>1</td></tr></table><div id="modal"></div><script>function neverDelete(){throw Error('NEVER_DELETE')} const data={entry:{time:'09:00:00',memo:'외출_담임:최유정(14:00~14:30)'},exit:{time:'18:00:00',memo:''}};function edit(f){const d=data[f];document.querySelector('#modal').innerHTML='<p>'+(f==='entry'?'1교시':'퇴실')+' 시간 수정</p><input id="name" disabled value="가상학생"><input id="prevTime" disabled value="'+d.time+'"><input id="modifyTime" value="'+d.time+'"><input id="memoByAdmin" value="'+d.memo+'"><button onclick="neverDelete()">삭제</button><button id="change">변경</button><button onclick="closeModal()">취소</button>';document.querySelector('#change').onclick=()=>{data[f]={time:document.querySelector('#modifyTime').value,memo:document.querySelector('#memoByAdmin').value};closeModal();};}function closeModal(){document.querySelector('#modal').innerHTML='';}function outing(){document.querySelector('#modal').innerHTML='<p>가상학생 님의 외출 시간 확인</p><table><tr><td></td><td>외출 시작 시간</td><td>외출 종료 시간</td><td>외출 종료 판단 기준</td><td>강의 시간 인정 여부</td></tr><tr><td></td><td>14:00:00</td><td>14:30:00</td><td>14:30:00</td><td>X</td></tr></table><button onclick="closeModal()">취소</button>';}</script></body></html>`);
    const c=new CheckHereCollector('',{page});page.setDefaultTimeout(3000);c.day={classId:'2',date:'2026-09-03',teacher:'최유정'};
    const rows=await c.tableRecords();assert.equal(rows.length,1);const r=await c.readDetails(rows[0]);assert.equal(r.readState,'complete',r.readError);assert.equal(r.entryMemo,'외출_담임:최유정(14:00~14:30)');assert.equal(r.exitMemo,'');assert.deepEqual(r.outings,[{start:'14:00:00',end:'14:30:00',cutoff:'14:30:00',recognized:false}]);
    await c.write(r,'exit',{time:'18:00:00',memo:'시스템오류_담임:최유정'});const after=await c.readDetails((await c.tableRecords())[0]);assert.equal(after.exitMemo,'시스템오류_담임:최유정');
    await assert.rejects(()=>c.modal({...r,name:'다른사람'},'entry'),/일치 확인 실패/);
  }finally{await browser.close();}
});

