import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync,mkdirSync} from 'node:fs';import {join} from 'node:path';import {loadPlaywright} from '../collector.mjs';
test('teacher home ordering, own-class statistics, survey charts, material links and synthetic student prototype',async()=>{
 const {chromium}=loadPlaywright(),browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1500,height:1000}}),base=join(import.meta.dirname,'../..'),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 try{await page.route('**/*',async route=>{const u=new URL(route.request().url());
  if(u.hostname==='www.gstatic.com')return route.fulfill({contentType:'text/javascript',body:`window.reads??=[];window.docs??={
 'classes/2':{coreLinks:{textbook:'https://drive.google.com/drive/folders/fixture'}},
 'timetableBetaPublished/2':{classId:'2',entries:[{id:'lesson',lectureId:'lecture',title:'자료 테스트',module:'직무특화',date:'2026-09-15',kind:'class',day:1,hours:8}]},
 'attendanceBetaSummaries/2':{classId:'2',version:'20260923-disease1',asOf:'2026-09-15',latestDate:'2026-09-15',dates:['2026-09-15'],students:[{id:'0_예시',name:'예시',firstDate:'2026-09-15',dropout:false,diseaseDates:['2026-09-10','2026-09-11','2026-09-14','2026-09-15'],history:{'2026-09-15':{raw:'출석',status:'출석',basis:'시트',review:false}}}]},
 'surveyBetaSummaries/2/surveys/event':{eventId:'event',classId:'2',title:'자료 테스트',date:'2026-09-15',syncedAt:'2026-09-15T00:00:00Z',answered:[{id:'0_예시',name:'예시'}],missing:[],review:[],excluded:[],unknown:[],eligibleCount:1,duplicateCount:1,invalidCount:0,scores:{scale:5,overallAverage:4.5,overallCount:2,overallSum:9,invalid:0,questions:[{id:'q1',kind:'overall',title:'종합 만족도',min:1,max:5,count:2,sum:9,average:4.5,distribution:[0,0,0,1,1]}]}}
 };export const doc=(db,...p)=>({path:p.join('/')}),collection=doc,serverTimestamp=()=>({seconds:1}),query=(r)=>r,where=()=>{},documentId=()=> '__name__';export async function getDoc(r){window.reads.push(r.path);const v=window.docs[r.path];return {data:()=>structuredClone(v),exists:()=>!!v}}export const getDocFromServer=getDoc;export async function getDocs(r){window.reads.push(r.path);return{docs:Object.entries(window.docs).filter(([k])=>k.startsWith(r.path+'/')).map(([k,v])=>({id:k.split('/').at(-1),data:()=>structuredClone(v)}))}}export const getDocsFromServer=getDocs;export function onSnapshot(){return()=>{}}export async function setDoc(r,v){window.docs[r.path]=structuredClone(v)}export async function runTransaction(){throw Error('unexpected')} `});
  if(u.pathname==='/')return route.fulfill({contentType:'text/html; charset=utf-8',body:`<meta charset="utf-8"><style>${readFileSync(join(base,'index.html'),'utf8').match(/<style>([\s\S]*?)<\/style>/)[1]}</style><link rel="stylesheet" href="/portal-layout.css"><div id="host"><header class="topbar"><div class="portal-brand"><span class="hint-wordmark">HINT</span><div><h1 class="title">운영포털</h1></div></div><div class="top-actions"><button>로그아웃</button></div></header><main class="page"><section class="card teacher-class-switch"><div>담당 반 선택</div><div class="field"><label for="teacherClassSelect">현재 반</label><select id="teacherClassSelect"><option value="2">2반</option><option value="3">3반</option></select></div></section><div class="urgent-stack"><div class="urgent-alert">긴급 공지 원본</div></div><section class="hero"><p class="eyebrow">MY CLASS</p><h2>2반 · 제조지능화</h2></section><div class="section-head"><h2>오늘 꼭 할 일</h2></div><section class="task-grid"><button id="original">시트 바로가기</button></section><div class="section-head"><h2>매일 공지</h2></div><section class="card notice"><p>공지 원본</p><button id="copyNotice">공지 복사</button></section></main></div><script type="module">import{mountTeacherWorkspace}from'/teacher-workspace.mjs';window.clicks=0;window.copies=0;window.classChanges=0;document.querySelector('#original').onclick=()=>window.clicks++;document.querySelector('#copyNotice').onclick=()=>window.copies++;document.querySelector('#teacherClassSelect').onchange=()=>window.classChanges++;await mountTeacherWorkspace(document.querySelector('#host'),{db:{},user:{email:'teacher@example.com'},classInfo:{id:'2',course:'제조지능화'}});</script>`});
  if(u.pathname==='/survey-catalog.json')return route.fulfill({json:{events:[{id:'event',classId:'2',date:'2026-09-15',title:'자료 테스트',url:'https://forms.gle/fixture'}],responseSources:[]}});
  const path=join(base,u.pathname.slice(1));if(u.hostname==='fixture.test'&&existsSync(path)&&/\.(mjs|js|css|html|json)$/.test(path))return route.fulfill({contentType:path.endsWith('.html')?'text/html; charset=utf-8':path.endsWith('.css')?'text/css':path.endsWith('.json')?'application/json':'text/javascript',body:readFileSync(path,'utf8')});return route.abort();
 });
 await page.goto('https://fixture.test/');await page.getByRole('heading',{name:'학생 출결현황'}).waitFor();await page.getByRole('heading',{name:'만족도조사 현황'}).waitFor();
 await page.getByText('예시 4/6회 (주의)').waitFor();await page.getByRole('button',{name:'질병 인정 현황',exact:true}).click();await page.getByRole('heading',{name:'질병 인정출석 제한위험자'}).waitFor();await page.getByRole('cell',{name:'4/6회'}).waitFor();await page.getByRole('button',{name:'우리 반 홈',exact:true}).click();
 const sections=await page.locator('[data-teacher-panel="home"]').evaluate(el=>Array.from(el.children).map(n=>n.shadowRoot?.textContent||n.textContent));assert(sections[0].includes('오늘의 수업'));assert(sections[1].includes('긴급 공지 원본'));assert(sections[1].includes('공지 원본'));assert(sections[2].includes('오늘 꼭 할 일'));assert(sections[4].includes('학생 출결현황'));assert(sections[5].includes('만족도조사 현황'));assert.equal(await page.locator('.topbar .teacher-header-class').count(),1);assert.equal(await page.locator('.topbar .top-actions #teacherClassSelect').count(),1);assert.equal(await page.locator('.page>.hero').count(),0);assert.equal(await page.locator('.daily-checklist').getAttribute('open'),null);assert.equal(await page.getByRole('button',{name:'체크리스트 복사',exact:true}).isVisible(),false);await page.getByText('일일 업무 체크리스트',{exact:true}).click();await page.getByRole('button',{name:'체크리스트 복사',exact:true}).click();await page.getByText('일일 업무 체크리스트',{exact:true}).click();assert.equal(await page.evaluate(()=>window.copies),1);await page.locator('#teacherClassSelect').selectOption('3');assert.equal(await page.evaluate(()=>window.classChanges),1);await page.locator('#teacherClassSelect').selectOption('2');
 await page.getByRole('button',{name:'시트 바로가기',exact:true}).click();assert.equal(await page.evaluate(()=>window.clicks),1);
 await page.getByRole('button',{name:'출결 통계',exact:true}).click();await page.getByRole('button',{name:'예시',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'선택 범위 출결 동기화'}).count(),0);await page.getByRole('button',{name:'예시',exact:true}).click();await page.getByRole('dialog').getByText('첫 출결 기록 2026-09-15').waitFor();await page.getByRole('button',{name:'닫기',exact:true}).click();
 await page.getByRole('button',{name:'만족도조사',exact:true}).click();await page.getByRole('button',{name:'응답률 · 만족도 통계'}).click();await page.getByRole('heading',{name:'우리 반 만족도 통계'}).waitFor();await page.getByRole('button',{name:'보기',exact:true}).click();await page.getByRole('heading',{name:'2반 · 자료 테스트',exact:true}).waitFor();assert(await page.getByText('4.5 / 5',{exact:true}).count()>0);
 await page.getByRole('button',{name:'강의자료',exact:true}).click();await page.getByRole('button',{name:'+ 자료 링크 연결'}).click();await page.getByLabel('자료 이름').fill('실습 교재');await page.getByLabel('Drive 파일 링크').fill('https://drive.google.com/file/d/fixture/view');await page.getByRole('button',{name:'연결 저장'}).click();await page.getByRole('link',{name:'실습 교재 ↗'}).waitFor();assert(await page.evaluate(()=>Object.keys(window.docs).some(k=>k.startsWith('lectureMaterialsBeta/2/items/'))));
 assert(!(await page.evaluate(()=>window.reads)).some(p=>/^classes\/(?!2(?:\/|$))|^attendanceBetaSummaries\/(?!2$)|^surveyBetaSummaries\/(?!2\/)/.test(p)));
 await page.getByRole('button',{name:'우리 반 홈',exact:true}).click();assert.equal(await page.locator('[data-teacher-panel]:visible').count(),1);mkdirSync(join(base,'checkhere/test-results'),{recursive:true});await page.screenshot({path:join(base,'checkhere/test-results/teacher-home-20260915.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('.topbar').evaluate(el=>el.scrollWidth>el.clientWidth+1),false);await page.screenshot({path:join(base,'checkhere/test-results/teacher-header-mobile.png'),fullPage:false});
 await page.goto('https://fixture.test/student-beta.html');await page.getByRole('button',{name:'가입 화면 미리보기'}).click();assert(await page.getByLabel('휴대전화').isDisabled());await page.getByRole('button',{name:'초안으로 돌아가기'}).click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(base,'checkhere/test-results/student-mobile-20260915.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
