import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {join} from 'node:path';import {loadPlaywright} from '../collector.mjs';
test('any administrator reads only identity columns, deduplicates, stores a scoped summary; teachers read summaries only',async()=>{
 const {chromium}=loadPlaywright(),browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage(),base=join(import.meta.dirname,'../..'),requests=[],errors=[];
 const catalog={events:[{id:'survey-2-1',classId:'2',date:'2026-09-03',title:'SW 테스팅',url:'https://forms.gle/fixture'}],responseSources:[{id:'response-1',title:'임베디드AI-HW(SW 테스팅)',sheetUrl:'https://docs.google.com/spreadsheets/d/fixture-response/edit'}]};
 page.on('pageerror',e=>errors.push(e.message));
 try{
 await page.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());requests.push({method:req.method(),url:u.href,at:Date.now()});
  if(u.hostname==='www.gstatic.com'&&u.pathname.endsWith('firebase-auth.js'))return route.fulfill({contentType:'text/javascript',body:`export class GoogleAuthProvider{addScope(){}setCustomParameters(){}static credentialFromResult(){return{accessToken:'fixture-only'}}}export async function reauthenticateWithPopup(){return{}}`});
  if(u.hostname==='www.gstatic.com')return route.fulfill({contentType:'text/javascript',body:`window.docs??={'timetableBetaPublished/2':{classId:'2',entries:[{id:'first-day',date:'2026-09-02',title:'SW 테스팅',module:'직무특화',day:1,kind:'class'},{id:'lesson',date:'2026-09-03',title:'SW 테스팅',module:'직무특화',day:1,kind:'class'}]},'settings/attendanceBeta_2_2026-09-03':{students:{'1_나':{sheetStatus:'인정출석',portalStatus:'인정지각'}}}};export const getDocsFromServer=(...a)=>getDocs(...a),getDocFromServer=(...a)=>getDoc(...a),onSnapshot=()=>()=>{};export const collection=(d,...p)=>({path:p.join('/')}),doc=collection,serverTimestamp=()=>({seconds:1}),documentId=()=> '__name__',where=(...args)=>args,query=(ref,...filters)=>({...ref,filters});export async function getDoc(r){if(r.path==='timetableBetaPublished/3')await new Promise(resolve=>setTimeout(resolve,700));const d=window.docs[r.path];return {exists:()=>!!d,data:()=>structuredClone(d)}}export async function getDocs(r){return{docs:Object.entries(window.docs).filter(([k])=>k.startsWith(r.path+'/')&&(!r.filters||k.split('/').at(-1).startsWith('attendanceBeta_2_'))).map(([k,v])=>({id:k.split('/').pop(),data:()=>structuredClone(v)}))}}export async function setDoc(r,d){window.docs[r.path]=structuredClone(d)}export async function runTransaction(db,fn){return fn({get:getDoc,set:setDoc})}`});
  if(u.pathname==='/')return route.fulfill({contentType:'text/html; charset=utf-8',body:`<div id="host"></div><script type="module">import{mountSurveys}from'/survey-view.mjs';const classes=[{id:'2',course:'임베디드 AI(HW)'},{id:'3',course:'임베디드 AI(SW)'}];window.mount=async teacher=>{window.work?.dispose();window.work=await mountSurveys(document.querySelector('#host'),{db:{},user:{email:teacher?'teacher@example.com':'fixture-admin@example.com',getIdToken:async()=>'fixture-token'},classes,teacherClass:teacher?classes[0]:null});};await window.mount(false);</script>`});
  if(u.pathname==='/survey-catalog.json')return route.fulfill({json:catalog});
  if(u.pathname==='/api/attendance-reader')return route.fulfill({json:{ok:true,attendance:[['이름','','','','9/2','9/3'],['가','','','','출석','결석'],['나','','','','결석','인정출석'],['다','','','','결석','결석']]}});
  if(u.hostname==='sheets.googleapis.com'){
   assert.equal(req.method(),'GET');assert(!req.postData());
   if(u.pathname.endsWith('/values:batchGet')){assert.deepEqual(u.searchParams.getAll('ranges'),["'설문지 응답 시트1'!B2:B5","'설문지 응답 시트1'!D2:D5","'설문지 응답 시트1'!A2:A5","'설문지 응답 시트1'!C2:C5","'설문지 응답 시트1'!F2:F5"]);return route.fulfill({json:{valueRanges:[{values:[['가',' 가 ','나','다']]},{values:[['2반','2. 교육장','1반','2반']]},{values:[['2026-09-03','2026-09-04','2026-09-03','2026-09-03']]},{values:[['010-0000-1001','010-0000-1001','010-0000-1002','010-0000-1003']]},{values:[['1','5','3','2']]}]}});}
   if(u.pathname.includes('/values/'))return route.fulfill({json:{values:[['타임스탬프','성함을 입력해주세요','전화번호','소속반','민감 설문내용','[종합 만족도] 과정 전반에 대해 만족하십니까?']]}});
   return route.fulfill({json:{sheets:[{properties:{sheetId:1,title:'설문지 응답 시트1',gridProperties:{rowCount:5,columnCount:6}}}]}});
  }
  const name=u.pathname.slice(1);if(['survey-identity.mjs','survey-sync-core.mjs','checkhere-snapshots.mjs','attendance-derived-core.mjs', 'attendance-derived-store.mjs', 'survey-scores.mjs', 'survey-statistics.mjs', 'attendance-statistics.mjs', 'metrics-ui.mjs', 'metrics.css', 'lecture-materials.mjs', 'checkhere/rules.mjs','survey-view.mjs','survey-core.mjs','survey-google.mjs','survey-store.mjs','survey.css','timetable-store.mjs','timetable-core.mjs','attendance-beta-core.mjs','attendance-io.mjs'].includes(name))return route.fulfill({contentType:name.endsWith('.css')?'text/css':'text/javascript',body:readFileSync(join(base,name),'utf8')});return route.abort();
 });
 await page.goto('https://fixture.test/');await page.getByRole('button',{name:'내 계정 응답 시트 연결'}).click();await page.getByRole('button',{name:'선택 반 응답 동기화',exact:true}).click();await page.getByText('대상 2명 · 응답 1명 · 미응답 1명').waitFor();
 const saved=await page.evaluate(()=>window.docs['surveyBetaSummaries/2/surveys/survey-2-1']);assert.deepEqual(saved.missing.map(s=>s.name),['나']);assert.equal(saved.duplicateCount,1);assert.equal(saved.scores.overallAverage,5);assert.deepEqual(saved.excluded.map(s=>s.name),['다']);assert(!JSON.stringify(saved).includes('fixture-only'));assert(!JSON.stringify(saved).includes('전화번호'));assert(!JSON.stringify(saved).includes('phoneLast4'));assert(!JSON.stringify(saved).includes('1001'));
 const googleReads=requests.filter(r=>r.url.includes('sheets.googleapis.com'));assert.equal(googleReads.length,3);for(let i=1;i<googleReads.length;i++)assert(googleReads[i].at-googleReads[i-1].at>=2400,'Google requests must be spaced');
 const started=Date.now();await page.getByRole('button',{name:'17개 반 순차 동기화',exact:true}).click();await page.getByText('2반 처리 완료 · 10초 후 3반을 이어서 수집합니다.').waitFor();assert(await page.getByRole('button',{name:'17개 반 순차 동기화',exact:true}).isDisabled());await page.waitForFunction(()=>!document.querySelector('#host').shadowRoot.querySelector('#surveyAll').disabled);assert(Date.now()-started>=9900,'next class must wait ten seconds');assert.equal(requests.filter(r=>r.url.includes('sheets.googleapis.com')).length,3,'reuse fresh source cache across class sync');
 await page.getByRole('combobox',{name:'반',exact:true}).selectOption('3');await page.getByText('선택한 반의 설문을 불러오는 중…').waitFor();assert(await page.getByRole('button',{name:'선택 반 응답 동기화',exact:true}).isDisabled());assert.equal(await page.getByText('대상 2명 · 응답 1명 · 미응답 1명').count(),0);await page.getByText('선택한 기간에 등록된 설문이 없습니다.').waitFor();
 const reads=requests.filter(r=>r.url.includes('sheets.googleapis.com')).length;await page.evaluate(()=>window.mount(true));await page.getByRole('heading',{name:'우리 반 만족도조사'}).waitFor();await page.getByText('대상 2명 · 응답 1명 · 미응답 1명').waitFor();assert.equal(await page.getByRole('button',{name:/동기화/}).count(),0);assert.equal(requests.filter(r=>r.url.includes('sheets.googleapis.com')).length,reads);assert.deepEqual(errors,[]);await page.evaluate(()=>window.work.dispose());
 }finally{await browser.close();}
});
