import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,mkdirSync} from 'node:fs';import {join} from 'node:path';import {loadPlaywright} from '../collector.mjs';
test('timetable imports, edits, conflict-checks, publishes and renders teacher mobile view',async()=>{
 const base=join(import.meta.dirname,'../..'),{chromium}=loadPlaywright(),browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>d.type()==='prompt'?d.accept('새 과정'):d.accept());
 try{
 await page.route('**/*',async route=>{const u=new URL(route.request().url());
  if(u.hostname==='www.gstatic.com')return route.fulfill({contentType:'text/javascript',body:`window.docs={};export const doc=(db,...p)=>({path:p.join('/')}),collection=(db,...p)=>({path:p.join('/')}),serverTimestamp=()=>({seconds:1});export async function getDoc(r){const d=window.docs[r.path];return{exists:()=>!!d,data:()=>structuredClone(d)};}export async function getDocs(r){return{docs:Object.entries(window.docs).filter(([k])=>k.startsWith(r.path+'/')).map(([k,v])=>({id:k.split('/').pop(),data:()=>structuredClone(v)}))};}export async function runTransaction(db,fn){const pending=[];const value=await fn({get:getDoc,set:(r,v)=>pending.push([r.path,v])});for(const[k,v]of pending)window.docs[k]=structuredClone(v);return value;}`});
  if(u.pathname==='/')return route.fulfill({contentType:'text/html; charset=utf-8',body:`<div id="host"></div><script type="module">import{mountTimetableAdmin,mountTeacherTimetable}from'/timetable.mjs';window.mountTeacher=()=>mountTeacherTimetable(document.querySelector('#host'),{db:{},user:{email:'teacher@example.com'},classInfo:{id:'1',course:'임베디드 AI(HW)'}});await mountTimetableAdmin(document.querySelector('#host'),{db:{},user:{email:'admin@example.com'},classes:Array.from({length:17},(_,i)=>({id:String(i+1),course:i===1?'제조지능화':'임베디드 AI(HW)',venue:'교육장'}))});</script>`});
  const name=u.pathname.slice(1);if(['timetable.mjs','timetable-store.mjs','timetable-core.mjs','timetable.css','timetable-seed.json','timetable-reference.mjs','timetable-reference.json'].includes(name))return route.fulfill({contentType:name.endsWith('.css')?'text/css':name.endsWith('.json')?'application/json':'text/javascript',body:readFileSync(join(base,name),'utf8')});return route.abort();
 });
 await page.goto('https://fixture.test/');await page.getByRole('button',{name:'엑셀 기준 17개 반 가져오기'}).click();await page.getByRole('status').getByText(/17\/17개 반 가져오기 완료/).waitFor();
 assert.equal(await page.evaluate(()=>Object.keys(window.docs).filter(k=>k.startsWith('timetableBetaDrafts/')).length),17);
 await page.getByRole('button',{name:'강사 관리',exact:true}).click();await page.getByRole('button',{name:'+ 강사 등록'}).click();await page.getByLabel('이름',{exact:true}).fill('시험 강사');await page.getByLabel('연락처',{exact:true}).fill('010-0000-0000');await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByText('시험 강사',{exact:true}).waitFor();
 await page.getByRole('button',{name:'반별 시간표',exact:true}).click();await page.locator('#classFilter').selectOption('1');await page.locator('#date').fill('2026-09-11');await page.locator('#date').dispatchEvent('change');await page.locator('[data-edit]').first().click();assert.deepEqual(errors,[]);await page.locator('#editor select[name=instructorId]').selectOption({label:'시험 강사'});await page.getByRole('button',{name:'편집본 저장',exact:true}).click();await page.getByRole('status').getByText(/편집본을 저장/).waitFor();
 assert.equal(await page.evaluate(()=>Object.keys(window.docs).filter(k=>k.startsWith('timetableBetaPublished/')).length),0);
 await page.getByRole('button',{name:'선택 반 담임에게 공개'}).click();await page.getByRole('status').getByText(/1\/1개 반 공개 완료/).waitFor();assert.equal(await page.evaluate(()=>JSON.stringify(window.docs['timetableBetaPublished/1']).includes('010-0000')),false);
 // A stale editor must not overwrite a concurrent administrative change.
 await page.locator('[data-edit]').first().click();await page.evaluate(()=>window.docs['timetableBetaDrafts/1'].revision++);await page.getByLabel('전달사항',{exact:true}).fill('stale change');await page.getByRole('button',{name:'편집본 저장',exact:true}).click();await page.getByRole('alert').getByText(/다른 관리자/).waitFor();await page.getByRole('button',{name:'취소',exact:true}).click();
 await page.getByRole('button',{name:'과정·강의 관리',exact:true}).click();await page.getByRole('button',{name:'+ 과정',exact:true}).click();await page.getByText('새 과정',{exact:true}).first().waitFor();
 await page.getByRole('button',{name:'담임 화면 미리보기',exact:true}).click();await page.getByRole('heading',{name:/오늘의 수업/}).waitFor();
 const out=join(base,'checkhere/test-results');mkdirSync(out,{recursive:true});await page.screenshot({path:join(out,'timetable-teacher-desktop.png'),fullPage:true});
 await page.evaluate(()=>window.mountTeacher());await page.getByRole('heading',{name:/오늘의 수업/}).waitFor();assert.equal(await page.getByText('010-0000-0000',{exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'편집본 저장'}).count(),0);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(out,'timetable-teacher-mobile.png'),fullPage:true});assert.equal(await page.locator('.mobile-list').isVisible(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
