const ADR_SHEET_ID='1rVwWjo6EOdlRoqtrZ4v4d68vXbC2Pw7HQ3zaNpKIE34';
const ADR_FIREBASE_KEY='AIzaSyBL8YBAPyoGlcVX7T3tjgazncMHjHUY1DE';
const ADR_PROJECT='knewdeal-portal';
const ADR_ADMIN=new Set(['hint.kpc@gmail.com','kpc.jtkim@gmail.com']);
const ADR_START=new Date('2026-07-27T00:00:00+09:00');
const ADR_RENAME_FROM='2026-08-27';
function adrJson_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function doPost(e){try{const p=JSON.parse(e.postData&&e.postData.contents||'{}'),auth=adrAuthorize_(p.idToken);if(p.action==='list')return adrJson_(adrList_(p,auth));if(p.action==='renameManual')return adrJson_(adrRenameManual_(p,auth));throw new Error('BAD_ACTION')}catch(err){return adrJson_({ok:false,error:String(err.message||err)})}}
function adrAuthorize_(idToken){if(!idToken)throw new Error('LOGIN_REQUIRED');const r=UrlFetchApp.fetch('https://identitytoolkit.googleapis.com/v1/accounts:lookup?key='+encodeURIComponent(ADR_FIREBASE_KEY),{method:'post',contentType:'application/json',payload:JSON.stringify({idToken}),muteHttpExceptions:true});if(r.getResponseCode()!==200)throw new Error('LOGIN_REQUIRED');const u=(JSON.parse(r.getContentText()).users||[])[0],email=String(u&&u.email||'').toLowerCase();if(!email)throw new Error('LOGIN_REQUIRED');if(ADR_ADMIN.has(email))return{email:email,role:'ADMIN'};const url='https://firestore.googleapis.com/v1/projects/'+ADR_PROJECT+'/databases/(default)/documents/users/'+encodeURIComponent(email),pr=UrlFetchApp.fetch(url,{headers:{Authorization:'Bearer '+idToken},muteHttpExceptions:true});if(pr.getResponseCode()!==200)throw new Error('PROFILE_NOT_FOUND');const f=JSON.parse(pr.getContentText()).fields||{},role=f.role&&f.role.stringValue||'',active=f.active&&f.active.booleanValue===true;if(!active||role!=='ADMIN')throw new Error('ADMIN_REQUIRED');return{email:email,role:role}}
function adrClassFields_(idToken,classId){const url='https://firestore.googleapis.com/v1/projects/'+ADR_PROJECT+'/databases/(default)/documents/classes/'+encodeURIComponent(classId),r=UrlFetchApp.fetch(url,{headers:{Authorization:'Bearer '+idToken},muteHttpExceptions:true});if(r.getResponseCode()!==200)throw new Error('CLASS_DOC_NOT_FOUND_'+classId);return JSON.parse(r.getContentText()).fields||{}}
function adrRootId_(idToken,classId,key){const f=adrClassFields_(idToken,classId),mv=f.coreLinks&&f.coreLinks.mapValue&&f.coreLinks.mapValue.fields||{},url=mv[key]&&mv[key].stringValue||'',m=String(url).match(/\/folders\/([A-Za-z0-9_-]+)/);if(!m)throw new Error(String(key).toUpperCase()+'_FOLDER_NOT_SET');return m[1]}
function adrOfficial_(classId){const sh=SpreadsheetApp.openById(ADR_SHEET_ID).getSheetByName('반정보');if(!sh)throw new Error('CLASS_INFO_SHEET_NOT_FOUND');const last=Math.min(Math.max(sh.getLastRow(),1),200),v=sh.getRange(1,1,last,10).getDisplayValues();for(let i=0;i<v.length;i++){const cells=v[i].slice(0,9).map(x=>String(x||'').trim()),hit=cells.some(x=>new RegExp('^0?'+classId+'\\s*반?$').test(x));if(hit){const name=String(v[i][9]||'').trim();if(name)return name}}throw new Error('OFFICIAL_CLASS_NAME_NOT_FOUND_'+classId)}
function adrWeek_(date){const d=new Date(date+'T00:00:00+09:00'),diff=Math.floor((d-ADR_START)/86400000);if(diff<0)throw new Error('DATE_BEFORE_COURSE');return Math.floor(diff/7)+1}
function adrChild_(folder,patterns){const it=folder.getFolders();while(it.hasNext()){const f=it.next(),n=f.getName().replace(/\s+/g,'').toLowerCase();if(patterns.some(p=>n.indexOf(p)>=0))return f}return null}
function adrDateFolder_(rootId,date){const root=DriveApp.getFolderById(rootId),week=adrWeek_(date),wk=adrChild_(root,['week'+week,'week_'+week,'week-'+week,'week('+week+')']);if(!wk)throw new Error('WEEK_FOLDER_NOT_FOUND');const mmdd=date.slice(5,7)+date.slice(8,10),m=String(+date.slice(5,7)),d=String(+date.slice(8,10)),patterns=[mmdd,m+d,m+'월'+d+'일',m+'.'+d,m+'-'+d,m+'_'+d].map(x=>String(x).replace(/\s+/g,'').toLowerCase()),df=adrChild_(wk,patterns);if(!df)throw new Error('DATE_FOLDER_NOT_FOUND');return df}
function adrFiles_(folder){const out=[],it=folder.getFiles();while(it.hasNext()){const f=it.next();out.push({fileId:f.getId(),name:f.getName(),mimeType:f.getMimeType(),createdAt:f.getDateCreated().toISOString(),updatedAt:f.getLastUpdated().toISOString(),size:f.getSize(),fileUrl:f.getUrl(),previewUrl:'https://drive.google.com/file/d/'+f.getId()+'/preview'})}out.sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));return out}
function adrList_(p,auth){const classId=String(p.classId||''),date=String(p.date||''),key=String(p.folderKey||'');if(!/^([1-9]|1[0-7])$/.test(classId)||!/^2026-\d{2}-\d{2}$/.test(date)||!['manualAttendance','recognition'].includes(key))throw new Error('BAD_INPUT');const rootId=adrRootId_(p.idToken,classId,key),folder=adrDateFolder_(rootId,date),files=adrFiles_(folder);return{ok:true,classId:classId,date:date,folderKey:key,officialClassName:adrOfficial_(classId),folderId:folder.getId(),folderUrl:'https://drive.google.com/drive/folders/'+folder.getId(),files:files,actorEmail:auth.email}}
function adrSafe_(s){return String(s||'').replace(/[\\\/:*?\"<>|]/g,' ').replace(/\s+/g,' ').trim()}
function adrExt_(name){const m=String(name||'').match(/(\.[A-Za-z0-9]{1,8})$/);return m?m[1].toLowerCase():''}
function adrDates_(fromDate,toDate){const out=[],a=new Date(fromDate+'T00:00:00+09:00'),b=new Date(toDate+'T00:00:00+09:00');for(let d=new Date(a);d<=b;d.setDate(d.getDate()+1)){const day=d.getDay();if(day===0||day===6)continue;out.push(Utilities.formatDate(d,'Asia/Seoul','yyyy-MM-dd'))}return out}
function adrRenameManual_(p,auth){const from=String(p.fromDate||ADR_RENAME_FROM),to=String(p.toDate||'');if(from<ADR_RENAME_FROM||!/^2026-\d{2}-\d{2}$/.test(from)||!/^2026-\d{2}-\d{2}$/.test(to))throw new Error('BAD_DATE_RANGE');const dates=adrDates_(from,to),changes=[],skipped=[],errors=[];for(let ci=1;ci<=17;ci++){const classId=String(ci),official=adrSafe_(adrOfficial_(classId));let rootId='';try{rootId=adrRootId_(p.idToken,classId,'manualAttendance')}catch(e){errors.push({classId:classId,error:String(e.message||e)});continue}for(const date of dates){let folder;try{folder=adrDateFolder_(rootId,date)}catch(e){const msg=String(e.message||e);if(msg==='WEEK_FOLDER_NOT_FOUND'||msg==='DATE_FOLDER_NOT_FOUND'){skipped.push({classId:classId,date:date,reason:msg});continue}errors.push({classId:classId,date:date,error:msg});continue}const files=adrFiles_(folder).filter(x=>String(x.mimeType||'').indexOf('application/vnd.google-apps.')!==0),mmdd=date.slice(5,7)+date.slice(8,10),multi=files.length>1;for(let i=0;i<files.length;i++){const meta=files[i],suffix=multi?' ('+(i+1)+')':'',next=official+'_'+mmdd+suffix+adrExt_(meta.name);if(meta.name===next){skipped.push({classId:classId,date:date,fileId:meta.fileId,reason:'ALREADY_NAMED',name:next});continue}try{DriveApp.getFileById(meta.fileId).setName(next);changes.push({classId:classId,date:date,fileId:meta.fileId,from:meta.name,to:next,order:i+1})}catch(e){errors.push({classId:classId,date:date,fileId:meta.fileId,error:String(e.message||e)})}}}}
return{ok:true,fromDate:from,toDate:to,renamed:changes.length,changes:changes,skipped:skipped,errors:errors,actorEmail:auth.email}}
