const SHEET_ID='1rVwWjo6EOdlRoqtrZ4v4d68vXbC2Pw7HQ3zaNpKIE34';
const FIREBASE_KEY='AIzaSyBL8YBAPyoGlcVX7T3tjgazncMHjHUY1DE';
const PROJECT='knewdeal-portal';
const ADMIN=new Set(['hint.kpc@gmail.com','kpc.jtkim@gmail.com']);
const COURSE_START=new Date('2026-07-27T00:00:00+09:00');

function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function doPost(e){try{const p=JSON.parse(e.postData&&e.postData.contents||'{}');const auth=authorize_(p.idToken,String(p.classId||''));if(p.action==='context')return json_({ok:true,officialClassName:officialClassName_(String(p.classId))});if(p.action!=='upload')throw new Error('BAD_ACTION');return json_(upload_(p,auth))}catch(err){return json_({ok:false,error:String(err.message||err)})}}
function authorize_(idToken,classId){if(!idToken)throw new Error('LOGIN_REQUIRED');const r=UrlFetchApp.fetch('https://identitytoolkit.googleapis.com/v1/accounts:lookup?key='+encodeURIComponent(FIREBASE_KEY),{method:'post',contentType:'application/json',payload:JSON.stringify({idToken}),muteHttpExceptions:true});if(r.getResponseCode()!==200)throw new Error('LOGIN_REQUIRED');const u=JSON.parse(r.getContentText()).users?.[0];const email=String(u?.email||'').toLowerCase();if(!email)throw new Error('LOGIN_REQUIRED');if(ADMIN.has(email))return{email,role:'ADMIN'};const url='https://firestore.googleapis.com/v1/projects/'+PROJECT+'/databases/(default)/documents/users/'+encodeURIComponent(email);const pr=UrlFetchApp.fetch(url,{headers:{Authorization:'Bearer '+idToken},muteHttpExceptions:true});if(pr.getResponseCode()!==200)throw new Error('PROFILE_NOT_FOUND');const f=JSON.parse(pr.getContentText()).fields||{};const role=f.role?.stringValue||'',active=f.active?.booleanValue===true,ids=[];['classId','primaryClassId'].forEach(k=>{if(f[k]?.stringValue)ids.push(String(f[k].stringValue))});['classIds','tempClassIds'].forEach(k=>(f[k]?.arrayValue?.values||[]).forEach(v=>ids.push(String(v.stringValue||''))));if(!active||role!=='TEACHER'||ids.indexOf(classId)<0)throw new Error('CLASS_NOT_ALLOWED');return{email,role}}
function classDoc_(idToken,classId){const url='https://firestore.googleapis.com/v1/projects/'+PROJECT+'/databases/(default)/documents/classes/'+encodeURIComponent(classId);const r=UrlFetchApp.fetch(url,{headers:{Authorization:'Bearer '+idToken},muteHttpExceptions:true});if(r.getResponseCode()!==200)throw new Error('CLASS_DOC_NOT_FOUND');return JSON.parse(r.getContentText()).fields||{}}
function recognitionRootId_(idToken,classId){const f=classDoc_(idToken,classId),url=f.coreLinks?.mapValue?.fields?.recognition?.stringValue||'',m=url.match(/\/folders\/([A-Za-z0-9_-]+)/);if(!m)throw new Error('RECOGNITION_FOLDER_NOT_SET');return m[1]}
function officialClassName_(classId){const sh=SpreadsheetApp.openById(SHEET_ID).getSheetByName('반정보');if(!sh)throw new Error('CLASS_INFO_SHEET_NOT_FOUND');const last=Math.min(Math.max(sh.getLastRow(),1),200),v=sh.getRange(1,1,last,10).getDisplayValues();for(let i=0;i<v.length;i++){const cells=v[i].slice(0,9).map(x=>String(x||'').trim()),hit=cells.some(x=>new RegExp('^0?'+classId+'\\s*반?$').test(x));if(hit){const name=String(v[i][9]||'').trim();if(name)return name}}throw new Error('OFFICIAL_CLASS_NAME_NOT_FOUND')}
function weekNumber_(date){const d=new Date(date+'T00:00:00+09:00'),diff=Math.floor((d-COURSE_START)/86400000);if(diff<0)throw new Error('DATE_BEFORE_COURSE');return Math.floor(diff/7)+1}
function findChildByPatterns_(folder,patterns){const it=folder.getFolders();while(it.hasNext()){const f=it.next(),n=f.getName().replace(/\s+/g,'').toLowerCase();if(patterns.some(p=>n.indexOf(p)>=0))return f}return null}
function dateFolder_(rootId,date){const root=DriveApp.getFolderById(rootId),week=weekNumber_(date),wk=findChildByPatterns_(root,['week'+week,'week_'+week,'week-'+week,'week('+week+')']);if(!wk)throw new Error('WEEK_FOLDER_NOT_FOUND');const mmdd=date.slice(5,7)+date.slice(8,10),m=String(+date.slice(5,7)),d=String(+date.slice(8,10)),patterns=[mmdd,(m+d).toLowerCase(),m+'월'+d+'일',m+'.'+d,m+'-'+d,m+'_'+d];const df=findChildByPatterns_(wk,patterns.map(x=>x.replace(/\s+/g,'').toLowerCase()));if(!df)throw new Error('DATE_FOLDER_NOT_FOUND');return df}
function safe_(s){return String(s||'').replace(/[\\\/:*?\"<>|]/g,' ').replace(/\s+/g,' ').trim()}
function ext_(name){const m=String(name||'').match(/(\.[A-Za-z0-9]{1,8})$/);return m?m[1].toLowerCase():''}
function upload_(p,auth){const classId=String(p.classId||''),student=safe_(p.student),date=String(p.date||'');if(!student||!/^2026-\d{2}-\d{2}$/.test(date))throw new Error('BAD_INPUT');authorize_(p.idToken,classId);const official=safe_(officialClassName_(classId)),rootId=recognitionRootId_(p.idToken,classId),folder=dateFolder_(rootId,date),mmdd=date.slice(5,7)+date.slice(8,10),fileName=official+'_'+student+'_'+mmdd+ext_(p.originalFileName),existing=folder.getFilesByName(fileName);if(existing.hasNext())throw new Error('DUPLICATE_FILE_EXISTS');const bytes=Utilities.base64Decode(String(p.base64||''));if(bytes.length>3*1024*1024)throw new Error('FILE_TOO_LARGE_3MB');const blob=Utilities.newBlob(bytes,String(p.mimeType||'application/octet-stream'),fileName),file=folder.createFile(blob);return{ok:true,fileName,fileId:file.getId(),fileUrl:file.getUrl(),officialClassName:official,student,date,folderId:folder.getId(),actorEmail:auth.email}}
